examples/poc/README.md

secret key is inconsistent with deployment:
https://github.com/kubernetes-sigs/llm-instance-gateway/blob/main/examples/poc/manifests/samples/vllm-lora-deployment.yaml#L54
https://github.com/kubernetes-sigs/llm-instance-gateway/blob/main/examples/poc/manifests/samples/vllm-lora-deployment.yaml#L108

fix: inconsistent secret key with deployment

---

pkg/ext-proc/handlers/request.go

I tested this by hard-coding(since we haven't integrated with LLMService CRD yet) a new targetModel different than the input and it worked.

Update targetModel in request body

---

.github/dependabot.yml

Fixes #56 
I've added dependabot for gomod deps updating weekly.

Add dependency updates

---

Makefile
client-go/applyconfiguration/api/v1alpha1/llmserverpool.go
client-go/applyconfiguration/api/v1alpha1/llmservice.go
client-go/applyconfiguration/internal/internal.go
client-go/clientset/versioned/clientset.go
client-go/clientset/versioned/typed/api/v1alpha1/api_client.go
client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_llmserverpool.go
client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_llmservice.go
client-go/clientset/versioned/typed/api/v1alpha1/llmserverpool.go
client-go/clientset/versioned/typed/api/v1alpha1/llmservice.go
client-go/informers/externalversions/api/v1alpha1/llmserverpool.go
client-go/informers/externalversions/api/v1alpha1/llmservice.go
client-go/informers/externalversions/generic.go
client-go/listers/api/v1alpha1/llmserverpool.go
client-go/listers/api/v1alpha1/llmservice.go
hack/update-codegen.sh

This is a minor adjustment to: https://github.com/kubernetes-sigs/llm-instance-gateway/pull/66
to make sure this works for following users also. (TY @liu-cong for catching this and fixing).
Also generated new files as dual purpose: 
- a way of validation that these changes work.
- needed to generate anyway

Makefile fixes with generated output

---

README.md

https://github.com/kubernetes/community/pull/8211

Change from SIG Apps to SIG Network

---

pkg/ext-proc/backend/endpointslice_reconciler.go
pkg/ext-proc/backend/inferencepool_reconciler.go

related issue #146 
Fix the short-circuit logic in InferencePoolReconciler.

Fix InferencePoolReconciler

---

api/v1alpha1/groupversion_info.go
api/v1alpha1/inferencemodel_types.go
api/v1alpha1/inferencepool_types.go
test/e2e/e2e_suite_test.go
test/e2e/e2e_test.go
test/utils/utils.go

Related to #156 
Updating the files that are not managed by auto-gen tooling, and small formatting changes to a comment.

Updating non-generated docs/ minor formatting

---

pkg/ext-proc/backend/inferencemodel_reconciler.go

inferencemodel_reconciler: Fix a log message

---

pkg/ext-proc/test/benchmark/benchmark.go
test/integration/hermetic_test.go

Using constants for the repeated values

---

site-src/guides/index.md

fixed a typo in the website documentation

fixed a typo - close a bash markdown

---

tools/dashboards/inference_gateway.json

[Metric] Add inference pool and request error metrics to the dashboard

---

pkg/epp/controller/inferencemodel_reconciler.go
pkg/epp/controller/inferencemodel_reconciler_test.go

this is a follow up pr to #397 after I reverted changes that were done in Reconcile func to reduce the conflicts with #393

predicate follow up PR to remove the check from Reconcile func

---

site-src/guides/index.md

updated cleanup section in quickstart

---

internal/tls/tls.go
pkg/body-based-routing/server/runserver.go
pkg/epp/server/runserver.go

Add library for generating self-signed cert

---

pkg/body-based-routing/server/runserver.go
test/integration/bbr/hermetic_test.go

Ref: #443 
For now, I have only added a success case. I plan to add a few more test cases once I implement support for metrics.

Add initial integration test for body-based routing extension

---

pkg/body-based-routing/handlers/server.go

[BBR] Fix bug where request trailers were not being handled

---

pkg/body-based-routing/handlers/server.go
pkg/body-based-routing/handlers/server_test.go

Added unit tests verify the logic to handle stream body buffer.

Add some more unit tests for BBR

---

config/charts/inferencepool/README.md
config/charts/inferencepool/templates/_validations.tpl
config/charts/inferencepool/templates/epp-deployment.yaml
config/charts/inferencepool/templates/epp-service.yaml
config/charts/inferencepool/templates/inferencepool.yaml
config/charts/inferencepool/values.yaml

helm-improvements

---

config/charts/body-based-routing/templates/bbr.yaml

Fix verbosity flag in BBR helm chart

---

config/charts/inferencepool/Chart.yaml
config/charts/inferencepool/templates/gke.yaml
config/charts/inferencepool/values.yaml

Also reset the versions to 0 (i.e., not released), when we release, they will be set.

add namespace parameter to ClusterPodMonitoring secret reference

---

hack/push-chart.sh
hack/release-quickstart.sh

Updating the regex for semver matching for the helm chart, and including BBR

More release updates

---

config/manifests/gateway/gke/healthcheck.yaml
site-src/guides/index.md

- Update GKE HealthCheckPolicy to have the correct inference pool name
- Add curl instruction for CPU model server

Minor fixes to the user guide

---

config/charts/body-based-routing/README.md
config/charts/body-based-routing/templates/gke.yaml
config/charts/body-based-routing/values.yaml

Verified this works in a GKE cluster
/assign @ahg-g

Fix parsing issue in BBR helm

---

config/manifests/vllm/gpu-deployment.yaml

fixed bug - sleep is expecting to get a string

---

config/charts/body-based-routing/README.md

BBR readme fixes

---

OWNERS_ALIASES

Adding 2 new reviewers to the reviewers alias

---

config/charts/body-based-routing/templates/istio.yaml

Update BBR istio.yaml to use FULL_DUPLEX_STREAMED mode

---

site-src/guides/index.md

This PR updates the docs - getting started guide to use the latest release

Getting started docs version bump

---

config/manifests/inferencemodel.yaml
config/manifests/vllm/gpu-deployment.yaml
pkg/epp/README.md
site-src/guides/adapter-rollout.md
site-src/guides/index.md

Fix the mistakes in the manifest and description to ensure that readers can successfully follow the step-by-step instructions.

fix manifests and description in the user guides

---

pkg/epp/controller/pod_reconciler.go
pkg/epp/datastore/datastore.go
pkg/epp/util/pod/pod.go
pkg/epp/util/podutils/podutils.go

share IsPodReady function between pod_reconciler and datastore, remove code duplication

moved IsPodReady func to podutils

---

test/integration/epp/hermetic_test.go

use unstructured instead of checking InferenceModel/InferencePool and unmarshalling to specific object

removed double loop on docs in hermetic test

---

pkg/epp/handlers/server.go

This looks like a copy paste error.

epp: return correct response for trailers

---

site-src/index.md

fix #749.
this link got broken when #537 was merged

fixed broken link to implementations

---

site-src/guides/index.md

Fixes: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/740

Update istio version

---

site-src/concepts/api-overview.md

docs: fixed inference pool docs

---

pkg/epp/scheduling/config.go
pkg/epp/scheduling/plugins/filter/filter.go
pkg/epp/scheduling/scheduler.go

This is a cleanup/refactor to make the sheddable filter reusable

Clean up filters

---

pkg/epp/util/env/env.go
pkg/epp/util/env/env_test.go

Refactored the environment variable utility (pkg/epp/util/env) to enhance code quality, readability, and maintainability.
Key changes:
- Introduced generic helper functions `parseEnvWithValue` and `getEnvWithParser` to centralize common logic for fetching and parsing environment variables, reducing code duplication.
- Standardized logging messages for consistency across all `GetEnv<Type>` functions.
- Added `GetEnvDuration`.

Refactor: Improve env utility

---

pkg/epp/datastore/datastore.go

current implementation leaves dangling go routines and structs which will consume resources and hold unused objects from being GCd

fixed datastore bug to clean all go routines when pool is unset

---

test/integration/epp/hermetic_test.go

This PR addresses a test flake observed in the EPP integration test `TestFullDuplexStreamed_KubeInferenceModelRequest` within `hermetic_test.go`. The flakiness was caused by non-deterministic ordering of headers in the `set_headers` field of the `ext_procv3.ProcessingResponse`'s `response_headers`. The diff in the test failure (linked in #843) clearly shows this issue.
To resolve this, `protocmp.SortRepeated` has been added to the `cmp.Diff` call for `[]*ext_procv3.ProcessingResponse`. This sorts the `set_headers` by their key before comparison. Within this context, the order of HTTP headers is not semantically significant so ignoring this in the test does not effect efficacy of the test assertions.
Fixes #843

Fix: Ignore header order in hermetic test

---

README.md

Updating readme to reflect llm-d collab!

---

pkg/epp/handlers/request.go
pkg/epp/handlers/response.go
pkg/epp/handlers/server.go
pkg/epp/handlers/server_test.go

Fixes: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/854

Chunk implementation

---

conformance/tests/basic/inferencepool_resolvedrefs_condition.go
conformance/utils/traffic/traffic.go

Quick code clean up to add boiler place header as well as remove empty comments.

chor(conformance): fix header and remove extra comments

---

pkg/epp/requestcontrol/director.go
pkg/epp/requestcontrol/plugins.go

renamed interface from PostResponsePlugin to PostResponse

---

site-src/guides/metrics.md
tools/alerts/alert.yaml

TESTED:
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/694

metrics: Add documentation for sample alert rules

---

Makefile
hack/run-e2es.sh

Backport #978 
* Add scripts for running e2es
* Only export some
* Move e2e script to hack
* Trigger CI
* Install kind and add boilerplate
* No sudo
---------

Backport PR 978 Add scripts for running e2es (#978)

---

OWNERS_ALIASES

Title says it all! Thanks and congrats Nir!
CC: @Jeffwan @ahg-g @danehans @nirrozenbaum

Adding Nir as a maintainer!

---

site-src/guides/index.md

docs: added gke clean up instructions

---

docs/proposals/1023-data-layer-architecture/README.md

- Explicitly include change to scraping mode as non-goal (feedback on #1023)
- Spelling errors

Tidy up Data Layer documentation

---

hack/release-quickstart.sh

Fixes: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1163

fix: set epp image tag when releasing

---

README.md

Join Slack badge is widely used in the community and is very inviting :)

added join slack badge to readme

---

docs/proposals/1199-inferencemodel-api-evolution/README.md

Updating tabs to spaces

---

cmd/epp/runner/runner.go
pkg/epp/handlers/request.go
pkg/epp/handlers/request_test.go
pkg/epp/handlers/server.go
pkg/epp/metadata/consts.go
pkg/epp/requestcontrol/director.go
pkg/epp/requestcontrol/director_test.go
pkg/epp/server/runserver.go
pkg/epp/server/server_test.go
test/e2e/epp/e2e_test.go
test/integration/epp/hermetic_test.go
test/integration/util.go

remove protocol specifics from cmd-line flags

---

docs/proposals/1199-inferencemodel-api-evolution/README.md

proposal's title was the wrong name, fixing to match directory name

Correcting title name

---

pkg/epp/plugins/plugin_state.go
pkg/epp/plugins/plugin_state_test.go

This PR improves the test coverage and readability of the PluginState tests
Fix: #1343

test: enhance plugin state test coverage and readability

---

pkg/bbr/handlers/request.go

Implements selective JSON unmarshaling using struct tags to extract only the 'model' field instead of full JSON parsing. 
Performance improvements:
- Small payloads (1KB): 2.1x faster (8.7 µs -> 3.8 µs), 14x less memory (5.2 KB → 368 B)
- Medium payloads (25KB): 1.4x faster (26.2 µs -> 18.5 µs), 35x less memory (12.7 KB → 368 B)
- Large payloads (200KB): 1.1x faster (130 µs -> 117 µs), 133x less memory (48.8 KB → 368 B)
- Very large payloads (1MB): 1.1x faster (754.7 µs -> 691 µs), 730x less memory (269 KB → 368 B)
The struct approach consistently uses ~368B regardless of payload size, while full unmarshaling scales linearly with input size. Memory allocations reduced from 100+ to just 10 per operation across all payload sizes.
Benchmark results (3 runs, Intel Core Ultra 7 165H):
```
$ go …
```

[BBR] perf: optimize model name extraction with selective JSON unmarshaling using struct tags

---

api/v1/inferencepool_types.go
apix/v1alpha2/inferencepool_types.go
config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml

feat: added shortname as alias

---

cmd/epp/runner/runner.go

feat: added env var for pool group

---

config/manifests/regression-testing/vllm/multi-lora-deployment.yaml
config/manifests/vllm/gpu-deployment.yaml
site-src/guides/inferencepool-rollout.md

/kind bug
gpu doesn't work with vllm beyond v0.8.5
Fixes #
```release-note
None
```

fix: ping to vllm v0.8.5

---

conformance/resources/base.yaml

/area conformance-test
w/ port is needed now.
Fixes #
```release-note
```

fix(conformance) add endpointConfig port in conformance test for v1 as it's required for service kind now.

---

config/charts/inferencepool/templates/epp-deployment.yaml

/kind bug
current code includes a critical bug - plugins file is fixed to default-plugins.
This fix allows setting custom plugins configuration
Fixes #
```release-note
NONE
```

allow setting custom plugins file through helm

---

config/charts/inferencepool/templates/inferencepool.yaml

/kind bug
previous helm install failed as missing port when extensionRef is a service
Fixes #
fix helm installation failure
```release-note
```

fix: fixed helm

---

config/manifests/gateway/envoyaigateway/gateway.yaml
config/manifests/gateway/envoyaigateway/httproute.yaml
hack/verify-manifests.sh

/kind feature
Added envoy proxy ai-gateway
Fixes #
```release-note
```

Added envoy proxy ai-gateway

---

pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
pkg/epp/scheduling/framework/plugins/picker/random_picker.go

/kind cleanup
Fixes # https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1552#discussion_r2333933669
```release-note
```

fix-import-groups

---

tools/dashboards/README.md

Fixes dashboards README metrics link fix
```release-note
```

docs: dashboards README metrics link fix

---

site-src/guides/serve-multiple-genai-models.md

/kind documentation
Removes duplicate content from multi-model serving guide.
N/A
```release-note
NONE
```

docs: remove duplication in multimodel serving guide

---

config/charts/inferencepool/templates/epp-deployment.yaml

/kind feature
There is an open issue for it
https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1569
Fixes #
```release-note
NONE
```

helm: add NAMESPACE env var to EPP deployment for pool namespace

---

hack/release-quickstart.sh
site-src/guides/index.md

/kind feature
update automatically the helm chart version used in the quickstart guide
**Which issue(s) this PR fixes**: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1494
Fixes #
```release-note
```

update automatically the helm chart version used in the quickstart guide
