kubernetes-sigs/gateway-api-inference-extension

examples/poc/ext-proc/cache/cache.go, examples/poc/ext-proc/main.go
This fixes the following issues when building the binary:
```
> go build -o /ext-proc
cache/cache.go:90:2: cacheKey declared and not used
./main.go:99:17: undefined: rest
./main.go:104:2: clientset declared and not used
./main.go:104:20: undefined: kubernetes
```
=> Fix build for ext-proc example

examples/poc/README.md
1. fixed broken image path
2. added some improves for poc markdown file
=> docs: markdown perfs

README.md
Adding a tad more details to the README, should potential contributors or interested parties land on the repo first.
=> Updating top level README

pkg/ext-proc/backend/metrics.go, pkg/ext-proc/backend/provider.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/response.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/scheduler.go
The updated also allows picking multiple preferred pods instead of one, which improves efficiency when combining with other filters. If we only return one, it's more likely this pod is not preferred by other filtering criteria.
Also updated log levels:
- Level 1, 2: For non-spammy logs like initialization
- Level 3+: For per request debug logs
- Level 4+: For per loop logs like periodically scrape metrics
I made some silly bugs in the initial implementation which caused some metric not getting updated. I was misled by my previous benchmark results, which had lots of errors in the external load balancer. This time I performed benchmarks within the cluster with no errors, and upgraded the benchmark tooling to https://github.com/GoogleCloudPlatform/ai-on-gke/tree/main/benchmarks/benchmark/too …
=> Improve the filter to return multiple preferred pods instead of one; also fix metrics update bug

pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/types.go, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/go.mod, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/filter_test.go, pkg/ext-proc/scheduling/scheduler.go, pkg/ext-proc/scheduling/types.go
Benchmark results for critical vs. sheddable requests.  Pls find more details of the benchmark in this doc: 
https://docs.google.com/document/d/11ALHEF-9yOaLdbHbDjBoTY6fzejoEKiSYHzWpWqe8ZY/edit?tab=t.0#bookmark=id.gx5ki34wov48
Critical request:
Sheddable requests:
Success ratio for sheddable requests:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9cbe49ed-7fff-021c-a18d-ee9a4aa90688"><div dir="ltr" style="margin-left:0pt;" align="center">
QPS | Success ratio
-- | --
1.5 | 100.00%
3 | 100.00%
4.5 | 100.00%
6 | 100.00%
9 | 100.00%
12 | 100.00%
15 | 100.00%
18 | 97.56%
21 | 77.33%
24 | 58.88%
27 | 49.11%
30 | 36.77%
33 | 27.79%
36 | 19.11%
39 | 15.10%
42 | 13.48%
45 | 13.11%
48 | 12.56%
51 | 10.59%
54 | 11.31%
57 | 9.35%
60 | 8.58%
</div></b>
=> Add priority based scheduling

pkg/README.md, pkg/manifests/ext_proc.yaml, pkg/manifests/gateway.yaml, pkg/manifests/patch_policy.yaml, pkg/manifests/traffic_policy.yaml
The circuit breaker and timeout values are heavy handed, and some may even be unnecessary. We can continue to iterate upon what is needed and at what values as we continue benchmarking, and adjust/trim as needed.
=> Adding circuit breaker and timeout layers to avoid Gateway 5xx errors.

.gitignore, Dockerfile, examples/poc/ext-proc/go.mod, pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/endpointslice_reconciler.go, pkg/ext-proc/backend/endpointslice_reconcilier_test.go, pkg/ext-proc/backend/fake.go, pkg/ext-proc/backend/llmlserverpool_reconciler_test.go, pkg/ext-proc/backend/llmserverpool_reconciler.go, pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/provider_test.go, pkg/ext-proc/backend/types.go, pkg/ext-proc/go.mod, pkg/ext-proc/main.go
Implementation to integrate LLMServerPool and Pod reconciliation into the I-GW EndpointPicker(ext-proc)
=> LLMServerPool Implementation

pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/provider_test.go
The current implementation will fail to start if fetching pod or metrics fails. Fetching metrics can fail due to 1) transient error 2) lora metrics are not available if dynamic lora is not enabled on the model server.
The binary can recover for 1) and degrade gracefully in 2). Therefore it's better to not block the process from starting.
=> Do not fail Init if fetch metrics fails. It can recover gracefully.

pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/datastore_test.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/main.go
This PR allows LLMService to be used, and weight splitting to be achieves when using the appropriately configured model name.
=> Integrating LLMService with weight splitting

go.mod, pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/fake.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/test/benchmark/benchmark.go, pkg/ext-proc/test/hermetic_test.go, pkg/ext-proc/test/utils.go
* Fix a bug in main and a couple tests
* Adjust the logging level to be consistent with the rest: use V(3) for request level info logs.
=> Fix build and test

examples/poc/manifests/vllm/vllm-lora-deployment.yaml, go.mod, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/backend/vllm/metrics_test.go
- switch to using upstream vllm with new metric
- use latest series in gauge metric vllm:lora_requests_info using the time value of the series
- Use label pair running_lora_adapters
- update vllm example deployment to use latest
Fixes #22
=> switch to using upstream vllm with new metric 

pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/response.go, pkg/ext-proc/handlers/response_test.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/scheduler.go, pkg/manifests/ext_proc.yaml
The PR adds a response body handler, which parses the inference response with `usage` stats such as `completion_tokens`.
This is the prerequisite for adding metrics such as per output token latency.
=> Add response body handler

.golangci.yml, Makefile, api/v1alpha1/inferencepool_types.go, config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml, pkg/ext-proc/main.go, pkg/ext-proc/test/hermetic_test.go
This does not fix all linter issues, just the ones in the main file. 
Much of them were just overly long lines.
Part of completing #124
=> Lint fixes/updating .golangci to not use deprecated linter

pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/scheduler.go
Part of https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/124
=> fixing some lint errors

.golangci.yml, Makefile, api/v1alpha1/inferencemodel_types.go, config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml, pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/endpointslice_reconciler.go, pkg/ext-proc/backend/inferencepool_reconciler.go, pkg/ext-proc/backend/vllm/metrics_test.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/main.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/filter_test.go, pkg/ext-proc/scheduling/scheduler.go, pkg/ext-proc/test/benchmark/benchmark.go, pkg/ext-proc/test/hermetic_test.go, pkg/ext-proc/test/utils.go, test/e2e/e2e_test.go, test/utils/utils.go
Fixed the rest of the lint errors and updating the linters to match what is typically used in other sub-projects and enable lint checks on presubmit.
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/124
=> Fixed the rest of the lint errors and updating the linters

examples/poc/manifests/inferencepool-with-model.yaml, pkg/README.md
address https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/135
Remove outdated configurations and ensure the tutorial runs smoothly
=> Remove outdated configurations and ensure the tutorial runs smoothly

pkg/README.md
This update is necessary because the Sample vLLM Application requires a Hugging Face Token for access. Without proper configuration, the deployment will fail to start. To improve the README's clarity, The PR includes the steps to create the necessary secret. 
Additionally, the wording was modified from "You can find a sample" to a more direct instruction: "Run the command directly," simplifying the user process.
fix: #135 The problem 4
=> Update README: Add Hugging Face Token Setup Instructions and Improve Deployment Instructions

pkg/ext-proc/backend/endpointslice_reconciler.go, pkg/ext-proc/backend/inferencemodel_reconciler.go, pkg/ext-proc/backend/inferencemodel_reconciler_test.go, pkg/ext-proc/backend/inferencepool_reconciler.go, pkg/ext-proc/main.go, pkg/manifests/ext_proc.yaml
Changes the EPP CLI flags and internal API fields related to the InferencePool ns/name that the EPP belongs to.
Fixes #150
=> Changes InferencePool EPP Flags

pkg/ext-proc/backend/endpointslice_reconciler.go, pkg/ext-proc/main.go
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/157
(the above issue is obsolete now that we are removing the field itself)
=> ext-proc: remove unused fields from EndpointSliceReconciler

pkg/ext-proc/backend/inferencepool_reconciler_test.go
While going through the codebase, I noticed that there was a unit test missing for InferencePoolReconciler updateStore logic (similar to InferenceModelReconciler). This PR adds that in.
=> ext-proc/backend: add unit test for InferencePoolReconciler

pkg/ext-proc/backend/inferencemodel_reconciler.go, pkg/ext-proc/backend/inferencemodel_reconciler_test.go, pkg/ext-proc/backend/inferencepool_reconciler.go, pkg/ext-proc/main.go
Follow up from https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/165
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/157
=> ext-proc: change Inference* APIs to use NamespacedName

pkg/manifests/ext_proc.yaml
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/173
cc @danehans @kfswain
=> manifests: remove unused curl image from EPP manifest

pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/datastore_test.go, pkg/ext-proc/health.go, pkg/ext-proc/main.go, pkg/manifests/ext_proc.yaml
Adds a health gRPC Server and refactors `main()` for better lifecycle management:
- Introduced a health gRPC server to handle liveness and readiness probes.
- Refactored main() to manage server goroutines using sync.WaitGroup.
- Added graceful shutdown for servers and controller manager.
- Improved logging consistency and ensured datastore readiness checks.
Fixes #96
Fixes #175
=> Adds Health gRPC Server and Refactors Main()

api/v1alpha1/inferencemodel_types.go, api/v1alpha1/inferencepool_types.go, config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml, config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
This addresses comments:
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/154/commits/3f971caccd22ef0cacb708005f67d86b20172c07#r1907775587
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/154/commits/3f971caccd22ef0cacb708005f67d86b20172c07#r1907785698
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/154/commits/3f971caccd22ef0cacb708005f67d86b20172c07#r1907790075
and other smaller ones (can make the list exhaustive if needed but they are mostly grammatical or more detailed wording
=> [v0.1 API Review] Grammatical fixes and TypedCondition creation/defaulting

README.md, docs/dev.md
This is the first attempt to define logging guidelines in our current code base. This is not meant to be perfect/permanent, but something that can improve our logging quickly.
I am happy to follow up with a PR to update logging once this is approved.
Related issue: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/108
cc @danehans @ahg-g
=> Add logging guidelines

Dockerfile, Makefile
Also remove stale comment & unused directive from Dockerfile.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> dev: respect the IMAGE args in Makefile

OWNERS, OWNERS_ALIASES
This formally adds a set of maintainers that have already been actively leading this project. Once this is broadly approved and merged, we can mirror this in k/org to make it easier to release v0.1 of the API.
=> Adding new maintainers

OWNERS
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/203 swapped us over to aliases (which is great) but there seems to be a bug where the aliases arent recognized, adding back myself and @ahg-g directly to the approvers file to keep PR's flowing & using [k8s-ci-robot](https://github.com/k8s-ci-robot) rather than having admins merge directly.
=> Adding myself & ahg-g to owners directly while we figure out alias bug

pkg/README.md, pkg/manifests/ext_proc.yaml, pkg/manifests/extension_policy.yaml
- Separates EnvoyExtensionPolicy custom resource from resources required to run EPP.
- Updates POC readme with steps to apply the new manifest.
Fixes #199 
Supports #77
=> Separates EnvoyExtensionPolicy from Ext Proc

pkg/README.md, pkg/manifests/ext_proc.yaml
- Fixing CRD installation to reference the directory with a `kustomize` file in it.
- updating readme to pull the raw yaml files directly from GH
- locking the EPP to a specific hash
=> More Getting Started updates

test/e2e/e2e_suite_test.go, test/e2e/e2e_test.go, test/testdata/client.yaml, test/testdata/envoy.yaml
Previously, `gomega.Eventually` would return `nil` even if a non-200 status code was returned in the curl request. This PR fixes:
- The conditional logic for checking the status code
- The return value when comparing the `targetModel` in the curl response to validate load-balancing functionality.
- Adds curl-specific timeout and interval.
Fixes #239
=> Fixes gomega.Eventually() in e2e Test

docs/proposals/003-model-server-protocol/protocol.md
This is adapted from the initial [doc](https://docs.google.com/document/d/18VRJ2ufZmAwBZ2jArfvGjQGaWtsQtAP6_yF2Xn6zcms/edit?tab=t.0)
I didn't include the ORCA load reporting section as it's not currently required by the inference extension, though parallel efforts are happening. The intention is to keep the scope of this protocol small and expand in the future if needed.
I see this as a very initial effort to define the contract, and is an evolving process to monitor industry trends and drive more unification.
=> Add Endpoint Picker Protocol Proposal

pkg/ext-proc/backend/endpointslice_reconciler.go
Requeue reconcile requests for endpointslice until the inferencepool is available
We still need to fix https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/151
=> Requeue reconcile requests for endpointslice until the inferencepool is available

test/e2e/e2e_test.go
=> Fix e2e test

docs/dev.md, pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/util/logging/logging_const.go
The metrics refresh logs are very spammy, it's important to use a high verbosity level for it, to differentiate from normal DEBUG logs.
=> Add TRACE log level for the metric refresh loop

docs/proposals/003-endpoint-picker-protocol/README.md, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/main.go, pkg/ext-proc/server/runserver.go, pkg/manifests/gateway/patch_policy.yaml, pkg/manifests/vllm/deployment.yaml, test/integration/hermetic_test.go, test/testdata/envoy.yaml
=> Update default target-pod and inject it into response metadata

.github/ISSUE_TEMPLATE/bug_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new-release.md, .gitignore, Makefile
- Added a `make artifacts` rule to generate release artifacts
- Issue template for the release
Fixes #263
=> Release setup

.github/ISSUE_TEMPLATE/new-release.md, Makefile, hack/release-quickstart.sh
- `.github/ISSUE_TEMPLATE/new-release.md`: Updates the release github template.
- `Makefile`: Adds targets to support initial release automation.
- `hack/release-quickstart.sh`: A script to automate quickstart guide changes required for a release.
fixes: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/291
=> feat: adds initial release automation

api/v1alpha1/inferencemodel_types.go, api/v1alpha1/inferencepool_types.go
Yeah, pretty small change, the one line above suffices I think. Heres a random emoji just cause:🪸
=> Fixing small linter complaints

site-src/concepts/api-overview.md
Quick PR for fixing a misspell in the API concepts overview page.
=> site-source: Fix 'Bakcground' misspell in API concepts page

.golangci.yml
since we are not enforcing a specific order of imports, it is already causing failed presubmit tests: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/286
=> Remove gci linter

pkg/ext-proc/backend/inferencemodel_reconciler.go, pkg/ext-proc/backend/inferencemodel_reconciler_test.go
- Updates InferenceModel reconciler to not return an error if the InferenceModel is not found.
- Updates InferenceModel reconciler to remove the InferenceModel from the datatstore if it's not found.
- Adds unit tests
Fixes #280
=> fix: adds ErrorNotFound Handling for InferenceModel Reconciler

site-src/concepts/roles-and-personas.md, site-src/implementations.md
Quick follow-up to #309 that fixes some low hanging fruit with the initial doc set.
=> site-src: Replace k8sgateway with kgateway & fix spelling in roles-and-personas.md

.github/ISSUE_TEMPLATE/new-release.md, hack/release-quickstart.sh, pkg/manifests/ext_proc.yaml
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/301 reverted EPP changes from a different PR. Since the EPP image was already loaded in my cluster nodes, e2e failed due to CLI flag changes in the reverted PR. For the main branch, the EPP imagePullPolicy should be `Always` to ensure cached images are not being used.
- Updates release script to use correct and latest vLLM image.
- Updates release script to use production instead of staging image registry.
=> Updates EPP Deployment and Release Doc/Script

pkg/ext-proc/backend/inferencemodel_reconciler.go, pkg/ext-proc/backend/inferencemodel_reconciler_test.go
Follow up to https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/286
=> Delete InferenceModels from the datastore when deletionTimestamp is set

go.mod, pkg/ext-proc/main.go
This is bit of an optimistic attempt of mine to push Zap through
since controllers typically use Zap these days AFAIK.
Feel free to push back since there is a potential issue with the flags not being compatible.
This is somehow mitigated by supporting `-v` manually.
Related to #251 
You can compare the output before vs after:
```
I0131 20:00:45.986907   15562 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0131 20:00:45.986921   15562 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0131 20:00:45.986926   15562 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0131 20:00:45.986931   15562 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false …
```
=> Actually init logging using Zap

pkg/ext-proc/internal/runnable/grpc.go, pkg/ext-proc/internal/runnable/leader_election.go, pkg/ext-proc/main.go, pkg/ext-proc/server/runserver.go, pkg/ext-proc/server/runserver_test.go, test/integration/hermetic_test.go
This is related to #251 
K8s logging [guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls) don't allow fatal logging calls. They can be replaced by the documented calls, but just returning errors properly is a cleaner solution. That is what this PR implements.
`ErrorS` is being used instead of fatal calls.
`errgroup.Group` is being used to manage goroutines and terminate on error.
Regarding testing, I don't have infrastructure to run more than unit tests right now, but I build the executable and tested it manually in the console, both for signal received scenario and failing to bind to a port. If there is a better solution to test this, let me know.
```
$ ./ext-proc -poolName …
```
=> Remove fatal log calls in executable code

hack/test-e2e.sh
Adds an e2e test script that supports the POC and e2e deployment modes, e.g. `gtw default/inference-gateway` or `svc default/envoy` for the endpoint IP/port.
=> feat: Adds e2e test script

Makefile
Adds the `image-load` and `kind-load` Make targets.
Fixes #287
=> feat: adds image-load and kind-load Make targets

pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/fake.go, pkg/ext-proc/backend/inferencemodel_reconciler.go, pkg/ext-proc/backend/inferencepool_reconciler.go, pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/response.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/health.go, pkg/ext-proc/main.go, pkg/ext-proc/metrics/metrics.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/scheduler.go, pkg/ext-proc/test/benchmark/benchmark.go, pkg/ext-proc/test/utils.go, pkg/ext-proc/util/logging/fatal.go, test/integration/hermetic_test.go
All logging calls are rewritten to use structured logging.
I did `go run k8s.io/klog/hack/tools/logcheck -check-structured ./...` and fixed all issues detected.
Related to #251
=> Use structured logging

pkg/ext-proc/main.go, pkg/ext-proc/server/runserver.go, pkg/manifests/gateway/patch_policy.yaml, test/integration/hermetic_test.go, test/testdata/envoy.yaml
Fixes #225 
By default, secure serving is enabled and the server will create a self-signed certificate. Users can also provide their own certificate by setting the certPath.
=> Add TLS support with self-signed certificate.

pkg/ext-proc/backend/datastore.go, pkg/ext-proc/backend/datastore_test.go, pkg/ext-proc/backend/fake.go, pkg/ext-proc/backend/inferencemodel_reconciler.go, pkg/ext-proc/backend/inferencemodel_reconciler_test.go, pkg/ext-proc/backend/inferencepool_reconciler.go, pkg/ext-proc/backend/inferencepool_reconciler_test.go, pkg/ext-proc/backend/pod_reconciler.go, pkg/ext-proc/backend/pod_reconciler_test.go, pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/provider_test.go, pkg/ext-proc/backend/types.go, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/health.go, pkg/ext-proc/main.go, pkg/ext-proc/scheduling/filter_test.go, pkg/ext-proc/scheduling/scheduler.go, pkg/ext-proc/server/runserver.go, pkg/ext-proc/server/runserver_test.go, pkg/ext-proc/test/benchmark/benchmark.go, pkg/ext-proc/test/utils.go, pkg/ext-proc/util/testing/wrappers.go, pkg/manifests/ext_proc.yaml, pkg/manifests/vllm/deployment.yaml, test/integration/hermetic_test.go
This PR removes the intermediate cache in provider, and consolidates all storage behind the datastore component. This limits what is now called provider into a pure probing controller. To validate the change, I tried to increase test coverage especially for the controllers, which uncovered a couple of bugs (I added comments pointing them out). 
The PR is long, but unfortunately there is no way around doing this refactor without such a significant change. The best way to approach this PR is to start by looking at the Datastore interface, which defines the contract for accessing all cached state related to the pool, the models and the pods. All accesses to the datastore are done only via this interface. The components that accesses the datastore are the controllers (pool, model and pod) and …
=> Consolidating all storage behind datastore

pkg/ext-proc/backend/fake.go, pkg/ext-proc/backend/provider.go, pkg/ext-proc/backend/provider_test.go, pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/backend/vllm/metrics_test.go, pkg/ext-proc/controller/inferencemodel_reconciler.go, pkg/ext-proc/controller/inferencemodel_reconciler_test.go, pkg/ext-proc/controller/inferencepool_reconciler.go, pkg/ext-proc/controller/inferencepool_reconciler_test.go, pkg/ext-proc/controller/pod_reconciler.go, pkg/ext-proc/controller/pod_reconciler_test.go, pkg/ext-proc/datastore/datastore.go, pkg/ext-proc/datastore/datastore_test.go, pkg/ext-proc/datastore/types.go, pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/health.go, pkg/ext-proc/main.go, pkg/ext-proc/scheduling/filter.go, pkg/ext-proc/scheduling/filter_test.go, pkg/ext-proc/scheduling/scheduler.go, pkg/ext-proc/server/runserver.go, pkg/ext-proc/test/benchmark/benchmark.go, pkg/ext-proc/test/utils.go, test/integration/hermetic_test.go
=> Added controller and datastore package

pkg/ext-proc/backend/vllm/metrics.go, pkg/ext-proc/controller/pod_reconciler_test.go, pkg/ext-proc/datastore/datastore.go, pkg/ext-proc/datastore/types.go
=> fix inference extension not correctly scrape pod metrics

pkg/ext-proc/handlers/request.go, pkg/ext-proc/handlers/response.go, pkg/ext-proc/handlers/server.go, pkg/ext-proc/metrics/README.md, pkg/ext-proc/metrics/metrics.go, pkg/ext-proc/metrics/metrics_test.go, pkg/ext-proc/metrics/testdata/request_error_total_metric, pkg/ext-proc/scheduling/scheduler.go, pkg/ext-proc/util/error/error.go
This change defines some general errors, the list might grow in the future if more finer error types are needed.
=> [Metrics] Add request error metrics

cmd/epp/main.go, docs/proposals/003-endpoint-picker-protocol/README.md, pkg/epp/handlers/request.go, pkg/epp/handlers/server.go, pkg/epp/server/runserver.go, pkg/epp/test/utils.go, test/integration/hermetic_test.go
=> Defining an outer metadata struct as part of the extproc endpoint picking protocol

README.md, docs/proposals/003-model-server-protocol/README.md, docs/proposals/004-endpoint-picker-protocol/README.md
The proxy protocol is now more comprehensive, worth splitting that into its own doc for each reference.
=> Split the proxy and model server protocols for easy reference

Dockerfile, Makefile
This avoids loading unnecessary libraries that can be source of security vulnerabilities.
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/344
=> Switch to gcr.io/distroless/static:nonroot base image

pkg/epp/handlers/server.go
When I send a request without request body, will always come up with an error like:
```shell
2025-02-23T10:30:23+08:00	ERROR	handlers/server.go:99	Cannot receive stream request
sigs.k8s.io/gateway-api-inference-extension/pkg/epp/handlers.(*Server).Process
/root/MyCOde/kuromesi.com/gateway-api-inference-extension/pkg/epp/handlers/server.go:99
github.com/envoyproxy/go-control-plane/envoy/service/ext_proc/v3._ExternalProcessor_Process_Handler
/root/go/pkg/mod/github.com/envoyproxy/go-control-plane/envoy@v1.32.4/service/ext_proc/v3/external_processor_grpc.pb.go:106
google.golang.org/grpc.(*Server).processStreamingRPC
/root/go/pkg/mod/google.golang.org/grpc@v1.70.0/server.go:1690
google.golang.org/grpc.(*Server).handleStream
/root/go/pkg/mod/google.golang.org/grpc@v1.70.0/server.go:1814 …
```
=> fix context canceled recv error handling

README.md
Adding a roadmap to the top level README to keep interested parties informed on the plans for IGW, ordered by priority.
=> Adding a roadmap to README

cmd/epp/main.go, pkg/epp/controller/inferencemodel_reconciler.go
added event predicate to inferencemodel reconciler.
the predicate verifies the inferencemodel ns equals the configured inferencepool ns and that it references the name of the configured inferencepool.
to avoid tricky bugs the predicate runs both on old object and new object in update func predicate.
fix #149
=> added inferencemodel predicate + minor changes in logging

site-src/guides/index.md
Disconnecting the current readme from the v0.1.0 release of the manifest. Will have a follow up PR to create a separate version locked getting started guide
=> Syncing getting started guide all to main

cmd/epp/main.go, pkg/epp/backend/provider_test.go, pkg/epp/controller/inferencemodel_reconciler.go, pkg/epp/controller/inferencemodel_reconciler_test.go, pkg/epp/controller/inferencepool_reconciler_test.go, pkg/epp/controller/pod_reconciler.go, pkg/epp/controller/pod_reconciler_test.go, pkg/epp/datastore/datastore.go, pkg/epp/datastore/datastore_test.go, pkg/epp/handlers/request.go, pkg/epp/server/runserver.go, pkg/epp/test/utils.go, pkg/epp/util/testing/diff.go, pkg/epp/util/testing/wrappers.go, test/e2e/e2e_suite_test.go, test/integration/hermetic_test.go
Currently the logic tracks the models by Spec.ModelName, since this is not guaranteed to be unique within the cluster, we could run into two issues:
1) If the model name changes on the same InferenceModel object, we don't delete the original model entry in the datastore. 
2) We don't enforce the semantics that the modelName with the oldest creation timestamp is retained. While the api is assuming that this is enforced by another controller via the Ready condition, we don't have this controller yet, and so currently the behavior is unpredictable depending on InferenceModel events order.
To address the above, the PR makes changes to both the InferenceModel reconciler and the Model APIs in the datastore to ensure thread safe updates of the entries. In the store, the sync.Map was replaced …
=> Fix InferenceModel deletion logic

api/v1alpha2/inferencepool_types.go
Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/385
/hold
@danehans
=> removed the EndpointPickerNotHealthy condition form pool status

test/integration/hermetic_test.go
Start by adding request total metrics, more validation will be added in follow up.
https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/326
=> [Metrics] Add metrics validation in integration test

pkg/epp/backend/fake.go, pkg/epp/backend/provider.go, pkg/epp/backend/provider_test.go, pkg/epp/backend/vllm/metrics.go, pkg/epp/controller/pod_reconciler_test.go, pkg/epp/datastore/datastore.go, pkg/epp/datastore/types.go
Currently the scrape port is stored in `PodMetrics`, which should be updated when targetPortNumber of inferencePool changed.
Also, currently the datastore stores all `PodMetrics` and return a reference of it when we try to read which in my opinion is not safe. This may cause inconsistency if we try to read and directly modify it in a goroutine. I think we should always return a copy and let the datastore control all write actions.
=> fix metric scrape port not updated when inference pool target port updated

api/v1alpha2/inferencemodel_types.go, config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml, pkg/epp/datastore/datastore.go, pkg/epp/datastore/datastore_test.go
Fix https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/426
Fix #408
=> make ModelName immutable and fix model weight

api/v1alpha2/inferencemodel_types.go, api/v1alpha2/inferencepool_types.go, api/v1alpha2/shared_types.go, api/v1alpha2/zz_generated.deepcopy.go, client-go/applyconfiguration/api/v1alpha2/extension.go, client-go/applyconfiguration/api/v1alpha2/extensionreference.go, client-go/applyconfiguration/api/v1alpha2/poolobjectreference.go, config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml, pkg/epp/controller/inferencemodel_reconciler.go, pkg/epp/datastore/datastore.go, pkg/epp/util/testing/wrappers.go, test/utils/wrappers.go
Although we had most of this validation for the PoolObjectRef, we did not for the ExtensionRef. We also renamed the go field name from TargetPortNumber to PortNumber, but missed the corresponding json tag, this also fixes that.
=> Consistent validation for reference types

pkg/epp/test/utils.go, pkg/epp/util/testing/wrappers.go, test/integration/hermetic_test.go
=> create pods during integration tests

body-based-routing.Dockerfile, cmd/body-based-routing/health.go, cmd/body-based-routing/main.go, pkg/body-based-routing/README.md, pkg/body-based-routing/handlers/request.go, pkg/body-based-routing/handlers/request_test.go, pkg/body-based-routing/handlers/response.go, pkg/body-based-routing/handlers/server.go, pkg/body-based-routing/server/runserver.go
=> Add code for Envoy extension that supports body-to-header translation

Makefile, cloudbuild.yaml
=> Add Makefile + cloudbuild configs for body-based routing extension

config/manifests/ext_proc.yaml, config/manifests/inferencemodel.yaml, config/manifests/vllm/cpu-deployment.yaml, config/manifests/vllm/gpu-deployment.yaml, site-src/guides/index.md
=> added cpu based example

api/v1alpha2/inferencepool_types.go, config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
Thanks to @nicolexin for finding this: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/446#pullrequestreview-2658642000
/cc @danehans @kfswain @ahg-g
=> Fixing default status on InferencePool

hack/release-quickstart.sh, site-src/guides/index.md, test/e2e/e2e_suite_test.go
after adding cpu based model server to quickstart guide, it is needed to fix a few places that uses the deployment filepath
=> fixed filepath that points to gpu based model server deployment in few places

api/v1alpha2/inferencepool_types.go
Thanks to @nicolexin for catching this!
/cc @kfswarin
=> Renaming conditions and reasons used in InferencePool status

config/manifests/inferencemodel.yaml
Without this the gateway will return 404, though WAI, this can often lead to confusion especially for the first time user that the base model is not supported.
=> Add the base model to InferenceModel sample manifest

config/manifests/inferencemodel.yaml
A follow up on https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/479#issuecomment-2717028402
Note our user guide uses the tweet-summary LoRA adapter as an example. If users follow the user guide carefully, they should not see the base model. This is just to avoid surprises for first time user if they see the base model and try to make a request like they normally do with any model server startup guides.
=> Add the base model of the cpu vllm sample app to InferenceModel.yaml

site-src/guides/index.md
Following the quickstart guide on a v1.27 cluster, I get:
```sh
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api-inference-extension/raw/main/config/manifests/vllm/gpu-deployment.yaml
...
strict decoding error: unknown field "spec.template.spec.initContainers[0].restartPolicy"
```
The model server init container requires [sidecar container](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) support.
This PR does the following:
- Updates the docs to state this requirement.
- Increases the indent of cluster requirements so they appear as sub-bullets when rendered.
=> Fix: Updates Docs for Sidecar Requirements

cmd/body-based-routing/main.go, pkg/body-based-routing/server/runserver.go
There could be a potential case where BBR and EPP run together in which case we don't want defaults to clash.
/assign @ahg-g
=> Switch default serving and health check ports for bbr

docs/proposals/004-endpoint-picker-protocol/README.md
=> Amend the endpoint picker protocol to support fallbacks and subsetting

Makefile
Ran the `make bbr-image-build` command with `export EXTRA_TAG=main` as per cloudbuild.yaml and verified the generated image has the `main` tag.
=> Update Makefile for BBR to ensure all proper tags are added

pkg/epp/handlers/server.go, pkg/epp/handlers/streamingserver.go
Only log errors on response, do not interfere with upstream response message.
=> Improve response handling issues.

cmd/body-based-routing/main.go, pkg/body-based-routing/handlers/request.go, pkg/body-based-routing/handlers/request_test.go, pkg/body-based-routing/metrics/metrics.go
=> Add metrics for BBR extension

pkg/epp/handlers/response.go, pkg/epp/handlers/response_test.go, pkg/epp/handlers/server.go, site-src/guides/metrics.md
Address https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/178
=> [Metrics] Add vLLM streaming support for metrics

Makefile, test/e2e/epp/e2e_suite_test.go, test/e2e/epp/e2e_test.go
=> added support for testing cpu example in e2e tests

go.mod
Update GO version for certain functions that are not supported in `1.23` such as testing.Context to not block `make test` from running.
=> Update GO version to 1.24

Dockerfile, Makefile
Latest commit failed image build: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-inference-extension-push-images/1900621912891985920
This should fix, also added image build to the `make test` command so it is part of our CI
=> Fixing image build and adding image building to test runs

Dockerfile, cmd/epp/main.go, pkg/epp/backend/metrics/metrics_spec.go, pkg/epp/backend/metrics/metrics_spec_test.go
Addendum to #461 to allow metric_spec to be nil for specific metric scraping.
=> Add nil option for metric_spec to specify metrics to not be scraped.

pkg/epp/server/controller_manager.go, pkg/epp/util/testing/wrappers.go, test/integration/epp/hermetic_test.go, test/integration/epp/test_suite.go
Another incremental cleanup to the integration tests.
@kfswain
=> Refactor beforeSuite in integration tests

mkdocs.yml, site-src/guides/index.md
- Adds mkdocs tabs support
- Updates the quickstart guide to use tabs to separate the GPU/CPU-based model server deployment modes.
Rendered quickstart with this change:
=> Docs: Uses tabs for quickstart model server options

config/manifests/vllm/cpu-deployment.yaml
this PR bumps vllm-cpu image to the latest image that was published yesterday (after testing that it's working).
as of now, they do not have the tag "latest" and therefore it's needed to specify the version.
I'll work with vllm community on publishing latest tag on every release as part of their CI/CD and then we can update our image to use "latest" tag.
until that happens, need to bump the version by PR
=> bump vllm-cpu image to latest

pkg/epp/handlers/streamingserver.go
Since the EPP can control the flow of ext-proc messages by calling [srv.Recv()](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/296247b07feed430458b8e0e3f496055a88f5e89/pkg/epp/handlers/streamingserver.go#L81), and we need to buffer the body messages anyway, io.Pipe is an over complication and we can simply use a byte array.
Additional Notes:
- io.Pipe used in this way can cause a race condition: if multiple go routines are created with writers in quick succession, there is a case where the thread scheduler will select a routine that has a writer out of order, and cause the corresponding reads to happen out of order, causing a bad json parse and a failure of the message read.
- A following PR is going to parse the `content-length` header and set the byte slice to …
=> Simplifying EPP-side buffer

Makefile, cloudbuild.yaml, config/charts/inferencepool/Chart.yaml, hack/push-chart.sh
@robscott this should push the chart to the staging repo on every commit.
=> Add inferencepool chart push mechanics

pkg/body-based-routing/handlers/server.go
Similar to #538 for EPP
/assign @kfswain
=> Simplify body streaming for BBR

pkg/epp/handlers/streamingserver.go
See the difference of the e2e request latency after this fix. Before the e2e latency was showing 1 hour (the max bucket)
=> Bug fix: Initialize RequestReceivedTimestamp

pkg/epp/handlers/response.go, pkg/epp/handlers/streamingserver.go, test/integration/epp/hermetic_test.go
- Update streaming integration test when the response includes usage, the DONE message is returned together with the last message. The end of stream contains empty message.
=> [Metrics] Handle vLLM streaming response in streaming server

cloudbuild.yaml, hack/push-chart.sh
v0 indicates dev version in semver.
The problem is that `helm push` doesn't allow setting more than one tag on a published helm chart, and currently the charts we have in the staging repo are tagged with the git commit hash, which is not practical to use, see below:
This PR tags the charts created from the main branch with v0 all the time (helm doesn't allow using version "main" like containers, and so using v0)
The dev epp version and chart would be installed as follows:
```
helm install vllm-llama-7b oci://us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/charts/inferencepool \
--version v0 \
--set inferencePool.name=vllm-llama-7b \
--set inferencePool.selector.app=vllm-llama2-7b
```
=> Tag the main version of the helm chart with v0

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/inferencepool.yaml, config/manifests/gateway/patch_policy.yaml, config/manifests/inferencepool.yaml
Part of https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/496
We will eventually remove buffered mode support
=> Default to streaming mode

config/charts/body-based-routing/.helmignore, config/charts/body-based-routing/Chart.yaml, config/charts/body-based-routing/README.md, config/charts/body-based-routing/templates/NOTES.txt, config/charts/body-based-routing/templates/bbr.yaml, config/charts/body-based-routing/values.yaml
Part of the work for #536
Plan on making a few more vars parameters (e.g ports) but want to get this in and pushed first.
=> Initial helm chart for bbr

config/manifests/gateway/patch_policy.yaml
Adding disclaimer to location where user would disable FULL_DUPLEX to indicate that Buffered communication between EPP <-> Proxy is no longer the default behavior
cc: @ahg-g
=> Adding deprecation notice of BUFFERED mode on patch policy.

config/manifests/inferencepool.yaml, pkg/epp/datastore/datastore.go, pkg/epp/datastore/datastore_test.go, pkg/epp/handlers/request.go, pkg/epp/handlers/response.go, pkg/epp/handlers/response_test.go, pkg/epp/handlers/server.go, pkg/epp/handlers/streamingserver.go, pkg/epp/handlers/streamingserver_test.go, test/integration/epp/hermetic_test.go
This PR allows requests that do not have a body or trailer to passthrough to a random endpoint. This operates under the assumption that bodyless messages will be GET requests for administrative endpoints (such as `/health` or `/v1/models`).
Enforcement will involve a something like: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/526
EPP path restrictions are still in progress
=> Allow bodyless requests to passthrough EPP

pkg/epp/backend/metrics/metrics.go, pkg/epp/backend/metrics/pod_metrics.go
This PR allows partial metric updates even if the PodMetricsClient returns an error due to failure in processing a subset of the metrics. A partial update is considered better than no update.
A practical issue this fixes is that in vllm v1, if LoRA adapter is not enabled, the lora metrics won't even show up. Therefore the metrics won't get refreshed.
This also helps with any transient error in missing a metric.
Note1: For the LoRA metric, technically we can have a flag to indicate whether we can skip scraping it. That can be a separate followup.
Note2: There should be a separate "conformance test" effort to make sure the supported model server emit the metrics required by our protocol. The PodMetricsClient shouldn't be responsible for that. Therefore it's safe to optimistically allow …
=> Allow partial metric updates

config/manifests/vllm/gpu-deployment.yaml
Model servers are production facing services, and should be configured in Kubernetes to not drop traffic or cause request errors during graceful rollout or predictable interruption (such as due to anticipated node maintenance from an admin).
Configure the default gpu_deployment.yaml example to accomplish hitless updates and graceful shutdown, and document *why* these values are chosen to allow others to determine best practices for model servers behind InferencePools. We should also update our documentation to describe these best practices once this configuration has been more widely validated
This PR:
* Tunes liveness and readiness checks based on the vLLM implementation and best practices
* Adds a startupProbe (see #558) that blocks regular liveness and readiness from being run until …
=> Configure the vllm deployment with best practices for startup

config/manifests/vllm/gpu-deployment.yaml
Until 0.8.3 is released, using the LoRA flag disables automatic
v1 opt-in.
=> Configure gpu-deployment.yaml to force vLLM v1 with LoRA

Makefile
makefile had two identical variable, one called PROJECT_DIR and another called ROOT_DIR (which I introduced when working on e2e tests and didn't notice the PROJECT_DIR var).
no need for both.
=> minor update to Makefile

config/charts/body-based-routing/README.md, config/charts/body-based-routing/templates/gke.yaml, config/charts/body-based-routing/templates/istio.yaml, config/charts/body-based-routing/values.yaml
/assign @ahg-g @kfswain @robscott
=> Add provider-specific manifests for BBR helm chart

config/charts/inferencepool/README.md, config/charts/inferencepool/values.yaml, config/manifests/benchmark/benchmark.yaml, config/manifests/gateway/patch_policy.yaml, config/manifests/inferencemodel.yaml, config/manifests/inferencepool.yaml, config/manifests/vllm/cpu-deployment.yaml, config/manifests/vllm/gpu-deployment.yaml, hack/test-e2e.sh, pkg/epp/datastore/datastore_test.go, pkg/epp/handlers/response.go, pkg/epp/handlers/response_test.go, site-src/guides/adapter-rollout.md, site-src/guides/index.md, site-src/guides/metrics.md, test/e2e/epp/README.md, test/e2e/epp/e2e_suite_test.go, test/integration/epp/hermetic_test.go, test/testdata/envoy.yaml, test/testdata/inferencepool-with-model-hermetic.yaml, tools/dynamic-lora-sidecar/deployment.yaml, tools/dynamic-lora-sidecar/sidecar/test_sidecar.py
Scrutiny here would be appreciated, this touches quite a bit of our documentation
=> Updating llama 2 7b to llama 3.1 8b Instruct and adding new LoRA adapters

pkg/epp/scheduling/filter.go, pkg/epp/scheduling/filter_test.go, pkg/epp/scheduling/scheduler.go, pkg/epp/util/env/env.go, pkg/epp/util/env/env_test.go
This pull request introduces a significant refactor to make scheduler configuration values dynamically configurable through environment variables. The changes include creating a new `Config` struct to hold configuration values, updating various functions to use these new configuration values, and adding utility functions to load configuration from environment variables.
Key changes include:
Configuration Management:
* Added `Config` struct to hold configuration values (`KVCacheThreshold`, `QueueThresholdCritical`, `QueueingThresholdLoRA`, `LoraAffinityThreshold`) and initialized it using environment variables (`pkg/epp/scheduling/scheduler.go`).
* Implemented utility functions `getEnvFloat` and `getEnvInt` to retrieve configuration values from environment variables with default fallbacks …
=> update algorithm parameters from env variables

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/NOTES.txt, config/charts/inferencepool/templates/_helpers.tpl, config/charts/inferencepool/templates/_validations.tpl, config/charts/inferencepool/templates/epp-deployment.yaml, config/charts/inferencepool/templates/gke.yaml, config/charts/inferencepool/templates/inferencepool.yaml, config/charts/inferencepool/values.yaml
This allows creating provider specific adjacent resources.
=> Added provider support to InferencePool helm chart

config/charts/body-based-routing/README.md, config/charts/body-based-routing/templates/bbr.yaml, config/charts/body-based-routing/templates/gke.yaml, config/charts/body-based-routing/templates/istio.yaml, config/charts/body-based-routing/values.yaml
=> Add support for configuring ports in BBR helm chart

site-src/guides/metrics.md
The switch to a controller-based getting started guide (#577) has made part of this metrics guide obsolete.
=> Removing obsolete part of metrics guide

config/manifests/vllm/gpu-deployment.yaml, site-src/guides/adapter-rollout.md, tools/dynamic-lora-sidecar/README.md, tools/dynamic-lora-sidecar/deployment.yaml, tools/dynamic-lora-sidecar/sidecar/sidecar.py, tools/dynamic-lora-sidecar/sidecar/validation.yaml
This pull request introduces a new feature to set a default base model for LoRA adapters, which simplifies the configuration by reducing repetition. The most important changes include updates to configuration files, documentation, and the sidecar code to support this new feature.
* [`config/manifests/vllm/gpu-deployment.yaml`](diffhunk://#diff-9a12f629948dbec50c5d41c1141f0ce12014fe0d524610db77ede6c1443e50d9R249-R254): Added `defaultBaseModel` field to specify a default base model for all adapters when not specified individually. Removed redundant `base-model` entries from individual adapters.
* [`site-src/guides/adapter-rollout.md`](diffhunk://#diff-2f91052e7cc98ad99f5595e2110becab22e7fe2021356acb60c9430447374184R36-R41): Updated ConfigMap examples to include the `defaultBaseModel` field …
=> Allow defining a default base model in the lora syncer configuration

config/manifests/gateway/httproute-with-timeout.yaml, config/manifests/gateway/httproute.yaml, config/manifests/inferencemodel.yaml
1. The InferencePool name referenced by the quick start guide (`https://github.com/kubernetes-sigs/gateway-api-inference-extension/raw/main/config/manifests/inferencepool-resources.yaml`) is no longer `vllm-llama2-7b`:
```
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
labels:
name: vllm-llama3-8b-instruct
spec:
targetPortNumber: 8000
selector:
app: vllm-llama3-8b-instruct
extensionRef:
name: vllm-llama3-8b-instruct-epp
```
2. The `food-review-1` model does not exist. Updates the `food-review` example InferenceModel to use the correct target model name:
```
$ kubextl exec deploy/vllm-llama3-8b-instruct -- curl 127.0.0.1:8000/v1/models | jq .
...
{
"id": "food-review",
"object": "model",
...
```
=> Docs: Quickstart Fixes

config/charts/inferencepool/templates/epp-deployment.yaml, config/manifests/inferencepool-resources.yaml
Fixes #548 
Tested 3 scenarios:
- Scale up to 4 replicas
- Scale down to 1 replica
- Rollout restart a single replica
There are small dips in the metric, but the largest dip was on scale up, so I believe the QPS dip is due to imperfect metric read as instances come up/down
=> Adding terminationGracePeriodSeconds to match vLLMs

pkg/epp/handlers/server.go, pkg/epp/handlers/streamingserver.go, pkg/epp/metrics/metrics.go, pkg/epp/metrics/metrics_test.go, pkg/epp/metrics/testdata/running_requests_metrics, site-src/guides/metrics.md
Tested locally and compare the result with vLLM requests count gauge metrics:
Blue Line: vLLM
Green Line: EPP
Resolve https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/593
=> Add running request gauge metric

pkg/epp/backend/metrics/logger.go, pkg/epp/metrics/metrics.go, site-src/guides/metrics.md, test/integration/epp/hermetic_test.go
resolve https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/599
=> [Metrics] Add number of ready pods metric for inference pool

config/manifests/vllm/gpu-deployment.yaml, tools/dynamic-lora-sidecar/README.md
Updates the adapter ConfigMap name since the [adapter rollout guide](https://gateway-api-inference-extension.sigs.k8s.io/guides/adapter-rollout/) refers to the adapter confimap as `vllm-llama3-8b-instruct-adapters`.
=> Fixes Adapter ConfigMap Name Refs

hack/release-quickstart.sh
Adding helm value replacement to release script
=> Update release script

test/e2e/epp/e2e_test.go, test/testdata/envoy.yaml
Moving to FULL DUPLEX STREAM as the default, and updating the base model + LoRA adapter caused the e2e tests to fall out of sync.
Fixes: #619
=> Update e2e test config

config/charts/body-based-routing/README.md, config/charts/body-based-routing/templates/gke.yaml, config/charts/body-based-routing/values.yaml
=> Patch main/d9f737 to 0.3 release

test/integration/bbr/hermetic_test.go, test/integration/epp/hermetic_test.go, test/integration/util.go
I'm going to be adding testing for streaming to BBR integration tests and will need some functions being used by the EPP tests. These utils were under pkg/epp/.. which didn't quite make sense since they were only used by integration tests so I moved the file to test/integration/...
/assign @kfswain
=> Move integration test utils to central package

pkg/body-based-routing/handlers/server.go, test/integration/bbr/hermetic_test.go, test/integration/util.go
=> Add integration tests to exercise streaming mode in BBR

pkg/epp/backend/metrics/logger.go, pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/server/runserver.go, test/integration/epp/hermetic_test.go
fix #647.
in some places in the code, there is a periodic task needs to be executed and the code is using time.sleep which is a bad practice.
for example, time.sleep may cause delays when receiving SIGTERM - if the go routine started the sleep section we will need to wait until sleep competes and only then the go routine will exist (due to context close).
the Go way for doing periodic task endlessly (until a cancel/close is received) is by using ticker.
=> removed time.sleep and using ticker instead

test/e2e/epp/e2e_suite_test.go, test/e2e/epp/e2e_test.go
fix #620 (follow up PR to https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/485#pullrequestreview-2682760174)
=> fix some issues in e2e tests

config/charts/inferencepool/templates/gke.yaml, config/manifests/gateway/gke/gcp-backend-policy.yaml
Logging dramatically reduces initial friction debugging and relative
to the cost to serve is fairly minor (about 2-5% overhead). Enable
by default as consistent with our guides.
=> deploy: Enable logging for GKE gateway by default

Makefile, bbr.Dockerfile, body-based-routing.Dockerfile
bbr dir was changed, but dockerfile wasn't updated accordingly.
since PR #664 was merged, all merged PRs are failing in `post-inference-extension-push-images`
=> fix bbr dockerfile that was broken in PR #664

config/manifests/vllm/cpu-deployment.yaml, test/e2e/epp/README.md, test/e2e/epp/e2e_suite_test.go, test/testdata/envoy.yaml, test/testdata/inferencepool-e2e.yaml
Fixed #227 
/assign @danehans 
See results of E2E run below using the CPU-based vLLM:
```
rramkumar@rramkumar:~/gateway-api-inference-extension$ export E2E_MANIFEST_PATH=config/manifests/vllm/cpu-deployment.yaml
rramkumar@rramkumar:~/gateway-api-inference-extension$ export E2E_NS=foobar
rramkumar@rramkumar:~/gateway-api-inference-extension$ make test-e2e
MANIFEST_PATH=/usr/local/google/home/rramkumar/gateway-api-inference-extension/config/manifests/vllm/cpu-deployment.yaml go test ./test/e2e/epp/ -v -ginkgo.v
=== RUN   TestAPIs
Running Suite: End To End Test Suite - /usr/local/google/home/rramkumar/gateway-api-inference-extension/test/e2e/epp
====================================================================================================================
Random Seed: 1744127212
Will …
```
=> Use dedicated namespace for e2e test code

config/manifests/inferencepool-resources.yaml, pkg/epp/controller/inferencepool_reconciler.go, pkg/epp/controller/inferencepool_reconciler_test.go, pkg/epp/server/controller_manager.go, pkg/epp/server/runserver.go, site-src/implementations/gateways.md
this PR handles few minor things:
- in the epp yaml the namespace flag is not set. in cmd/main it DOES have a default value set for using `default` namespace. having said that, I tried few days ago to follow the getting started guide while deploying to another namespace. overall it went fine, but it took me a while to recall this flag has to be set. in our docs and examples we assume using default namespace, but when users deploy GIE in their envs, this is unlikely. I think poolNamespace flag should be passed explicitly to allow relatively easy way to change the used namespace (I don't expect a newcomer who tries following the getting started guide to get into code and understand they need to add this flag).
- remove PoolNamespacedName from InfPool Reconciler, it's not in use since we …
=> minor changes in few places

site-src/guides/index.md
Adds Kgateway cleanup instructions to the quick start guide.
=> Docs: Adds Kgateway Cleanup to Quickstart

cmd/epp/main.go, pkg/epp/backend/metrics/logger.go, pkg/epp/server/runserver.go, test/integration/epp/hermetic_test.go
metrics logger is trashing the epp log. so instead of allowing a focused view of what changed, the epp log looks like this:
```
{"level":"Level(-3)","ts":"2025-04-17T21:04:48Z","caller":"metrics/logger.go:101","msg":"Flushing Prometheus Metrics","ReadyPods":1}
{"level":"Level(-3)","ts":"2025-04-17T21:04:53Z","caller":"metrics/logger.go:101","msg":"Flushing Prometheus Metrics","ReadyPods":1}
{"level":"Level(-3)","ts":"2025-04-17T21:04:58Z","caller":"metrics/logger.go:101","msg":"Flushing Prometheus Metrics","ReadyPods":1}
{"level":"Level(-3)","ts":"2025-04-17T21:05:03Z","caller":"metrics/logger.go:101","msg":"Flushing Prometheus Metrics","ReadyPods":1}
{"level":"Level(-3)","ts":"2025-04-17T21:05:08Z","caller":"metrics/logger.go:101","msg":"Flushing Prometheus Metrics","ReadyPods":1} …
```
=> reduce log level in metrics logger not to trash the log

pkg/epp/controller/inferencemodel_reconciler_test.go, pkg/epp/controller/inferencepool_reconciler.go, pkg/epp/controller/pod_reconciler.go, pkg/epp/controller/pod_reconciler_test.go, pkg/epp/datastore/datastore.go, pkg/epp/datastore/datastore_test.go, pkg/epp/util/pod/pod.go
this PR does the following changes:
- in podutil package, changed `IsPodReady` function to check if pod is marked for deletion. up until today storing pods logic in datastore was inconsistent in a way that  `pod_reconciler` checked this condition, but if there was a change in InfPool that triggered podResync (i.e label selector change), the deletion timestamp was not checked, which may lead to adding pods that are marked for deletion to the datastore. `IsPodReady` function in GIE serves for the purpose of answering the question - "can this pod serve requests" and  the functionality should be consistent whether pod is updated or pool selector is updated.
- remove unused pool arg from `PodUpdateOrAddIfNotExist` function in datastore. updated all calls accordingly. 
- Upon setting the pool …
=> few updates in datastore

pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/backend/metrics/types.go, pkg/epp/scheduling/plugins/filter/filter.go, pkg/epp/scheduling/plugins/filter/filter_test.go, pkg/epp/scheduling/plugins/noop.go, pkg/epp/scheduling/plugins/picker/random_picker.go, pkg/epp/scheduling/plugins/plugins.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go
This PR does a restructuring of the scheduler existing code. for example moving plugins interfaces from `scheduling/types/interfaces.go` to `/scheduling/plugins/plugins.go`. no code changes in this aspect of restructuring.
additionally, it adds some small changes, like the removal of return error from filter, scorer and picker interfaces since it was never used. tests were updated accordingly.
=> scheduler restructuring

pkg/epp/controller/pod_reconciler.go, pkg/epp/datastore/datastore.go
Pod controller only need to care about pods that related to inferencepool. So we can prevent these irrelevant pods enter in queue.
=> filter irrelevant pods in pod controller

pkg/epp/handlers/request.go, pkg/epp/handlers/server.go, pkg/epp/handlers/streamingserver_test.go
Update `GetRandomPod()` to return `nil` if no pods exist in the datastore. `HandleRequestHeaders()` will return an internal error when no Pods exist.
Fixes #727
=> EPP: Update GetRandomPod() to return nil if no pods exist

Makefile
this is very useful during development
=> added a target dedicated for running unit-test only

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/config.yml
This indirection allows us to apply labels on _all_ issues being created, making triage simpler.
=> Fixing errors in new template & disabling the default blank template

pkg/epp/scheduling/plugins/picker/max_score_picker.go, pkg/epp/scheduling/plugins/picker/random_picker.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go
This PR adds max score picker functionality.
if there is more than one pod with the highest score, it choses randomly between those pods.
additionally, the PR embeds Pod interface in the ScoredPod as suggested by @liu-cong in code review of previous PR.
=> add max score picker

pkg/epp/util/env/env.go, pkg/epp/util/env/env_test.go
This is the most basic env var format we should support...
I plan to use this to turn on the prefix aware routing feature in a follow up pr
=> Add GetEnvString helper function

pkg/epp/backend/metrics/fake.go, pkg/epp/backend/metrics/metrics.go, pkg/epp/backend/metrics/metrics_test.go, pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/backend/metrics/types.go, pkg/epp/backend/pod.go, pkg/epp/handlers/server.go, pkg/epp/scheduling/plugins/filter/filter_test.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go, test/integration/epp/hermetic_test.go
This PR extracts the Pod minimal representation from backend/metrics to backend.
I'm working on other PRs that implement scraper concept to allow extensibility for pod scraping.
for the use of this, it's useful to reuse the same pod definition. 
since this change touches a lot of files that are using the pod definition, it makes sense to push it in a separate PR.
=> extract pod representation from backend/metrics to backend

site-src/implementations/gateways.md
Hi maintainers,
Alibaba Cloud Container Service for Kubernetes (ACK)  has just released ACK Gateway with Inference Extension, which implements Gateway API inference extension. The component utilize InferencePool and InferenceModel API to help our customers optimize their routing solution for inference workloads (Please refer to [the usage doc](https://www.alibabacloud.com/help/en/ack/ack-managed-and-ack-dedicated/user-guide/intelligent-routing-and-traffic-management-with-ack-gateway-inference-extension#6ab3e971bfp3v)).
We sincerely request that ACK Gateway with Inference Extension be added to the implementation list of Gateway API inference extensions, and we look forward to contributing the customers requirements of Alibaba Cloud to the community.
@kfswain @liu-cong
=> Request for adding Alibaba Cloud Container Service for Kubernetes (ACK) into implementations

Dockerfile, cmd/epp/main.go, pkg/epp/metrics/metrics.go, site-src/guides/metrics.md
Start with just commit, version information will be added in a follow-up change.
Verified:
```
inference_extension_info{commit="60f8c57bb95b656a75d27564d5ff01c060bcdba5"} 1
```
Partially Fixes https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/579
=> Add inference_extension_info metric for project metadata

pkg/epp/scheduling/config.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_test.go
This makes the `SchedulerConfig` fields public so that they can customized by a caller (since the type itself, and then `NewSchedulerWithConfig` are both public I assume this was the original intention anyhow).
=> chore: make SchedulerConfig fields configurable

pkg/bbr/handlers/server.go, pkg/epp/handlers/server.go, pkg/epp/util/request/headers.go, pkg/epp/util/request/headers_test.go
Provide an util function to extract `x-request-id` from request when request headers are coming, and expose `x-request-id` in contextual loggers. This mechanism is adde to both EPP and BBR.
This resolves https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/556.
=> Parse request x-request-id and expose it in contextual logger

pkg/epp/scheduling/config.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_test.go
=> put SchedulerConfig fields private again. added NewSchedulerConfig func

pkg/epp/handlers/request.go, pkg/epp/scheduling/config.go, pkg/epp/scheduling/types/types.go
This PR makes request headers available in SchedulingContext (for use of scheduler plugins).
additionally, it fixes some minor typos and cosmetics.
=> passing headers to scheduler plugins

test/e2e/epp/e2e_suite_test.go, test/e2e/epp/e2e_test.go
Running `make test-e2e` results in:
```sh
STEP: Verifying connectivity through the inference extension @ 05/07/25 08:09:31.18
[FAILED] in [It] - /Users/solo-system-dhansen/go/src/sigs.k8s.io/gateway-api-inference-extension/test/e2e/epp/e2e_test.go:89 @ 05/07/25 08:12:31.183
STEP: Deleting the InferenceModel test resource. @ 05/07/25 08:12:31.183
• [FAILED] [180.340 seconds]
InferencePool when The Inference Extension is running [It] Should route traffic to target model servers
/Users/solo-system-dhansen/go/src/sigs.k8s.io/gateway-api-inference-extension/test/e2e/epp/e2e_test.go:47
[FAILED] Timed out after 180.001s.
Expected success, but got an error:
<*errors.errorString | 0x14000a84730>:
did not get 200 OK: HTTP/1.1 404 Not Found
date: Wed, 07 May 2025 15:12:26 GMT
server: uvicorn …
```
=> e2e: Fixes 404 Not Found Error

pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/backend/pod.go, pkg/epp/scheduling/scheduler_test.go
this PR fix a bug in cloning the pod's labels.
the bug was that labels value is assigned from one map to another.
this copies a pointer to the map (both vars are sharing the map), two problems with that:
1. if the map will change due to pod labels change and reconcile event at the same time a plugin access that map with no locking mechanism, it may cause issues (read & write in parallel to labels map without sync).
2. pod's labels may change during the scheduling cycle which is no good cause it may cause inconsistencies in the scheduler plugins.
this PR clones the labels to fix it.
=> fix labels not cloned bug

Dockerfile, bbr.Dockerfile
This PR addresses the following issue.
https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/698
=> Optimize Dockerfile for Multiple Extensions

pkg/epp/util/env/env.go
the separation seems unnecessary. 
there is no place where one call is done without the other + the code is very simple a short.
no logic change.
=> merge functions in env utils

pkg/epp/scheduling/plugins/prefix/plugin.go, pkg/epp/scheduling/plugins/prefix/plugin_test.go, pkg/epp/scheduling/types/cycle_state.go, pkg/epp/scheduling/types/scheduling_context.go, pkg/epp/scheduling/types/types.go
this PR aims to generalize scheduling CycleState inspired by the kube-scheduler framework CycleState.
the idea here is that the CycleState doesn't not necessarily map data from plugin name to its relevant state. 
it could be more generalized structures, for example adding headers field that can be consumed by the `schedule` caller.
additionally, it switches to using sync.map and interface similar to kube-scheduler. 
as of today, all scheduler plugins are running sequentially, but this can be easily changed to run plugins of the same type in parallel (e.g., each scorer is independent so it's possible to run all scorers in parallel to optimize response time).
This is part of a series of PRs that generalize scheduler and allow its extensibility in an easy and intuitive way.
=> generalize scheduling cycle state concept

pkg/epp/requestcontrol/director.go, pkg/epp/scheduling/plugins/filter/filter_test.go, pkg/epp/scheduling/plugins/filter/lora_affinity_filter.go, pkg/epp/scheduling/plugins/prefix/plugin.go, pkg/epp/scheduling/plugins/prefix/plugin_test.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go
This PR removes the `Model` field from `Scheduling.LLMRequest` struct.
from the scheduler point of view, it doesn't care about the original requested model name, only about the resolved model after traffic splitting that was done in a higher level.
we can see that `Model` field was used in unit-tests only and that it's always set to be identical to ResolvedTargetModel. Scheduler doesn't use this field.
In addition to removing `Model` field from `LLMRequest` struct, this PR renames `ResolvedTargetModel` to `TargetModel` in `LLMRequest` from the same reasons. scheduler plugins don't care about traffic splitting and "resolved" model, only about what is target model.
unit-tests and other usage places were updated accordingly.
=> remove Model field from LLMRequest

docs/proposals/005-prefix-cache-aware-routing-proposal/README.md, docs/proposals/0602-prefix-cache-aware-routing-proposal/README.md
This proposal was initially discussed in https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/498
=> Add prefix aware request scheduling proposal

config/manifests/gateway/kgateway/httproute.yaml, site-src/guides/index.md
- Updates the getting started guide to use Kgateway v2.0.2.
- Removes the port specifier workaround in the example Kgateway httproute.
=> Docs: Bumps Kgateway to v2.0.2

pkg/epp/backend/metrics/fake.go, pkg/epp/backend/metrics/metrics.go, pkg/epp/backend/metrics/metrics_state.go, pkg/epp/backend/metrics/metrics_test.go, pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/backend/metrics/pod_metrics_test.go, pkg/epp/backend/metrics/types.go, pkg/epp/datastore/datastore_test.go, pkg/epp/metrics/collectors/inference_pool_test.go, pkg/epp/scheduling/plugins/filter/filter_test.go, pkg/epp/scheduling/plugins/scorer/kvcache_test.go, pkg/epp/scheduling/plugins/scorer/queue_test.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go, test/integration/epp/hermetic_test.go
This PR renames the struct `Metrics` (under backend/metrics) to `MetricsState` and move it to a separate file (extracted from `types.go`).
currently in the repo there are many different places that uses the terminology 'metrics', which makes it confusing to a newcomer to understand where do we define what metrics we collect, and where is the metrics latest state.
This PR aims to solve this issue, as the changed struct holds the state of the scraped metrics from a pod (the values may change every scraping internal).
Additionally, not only this change improves readability of current code, it's also a first PR out of a bigger change. 
on follow up PRs, the concept of ServerState (a general purpose interface) will be introduced and is representing a state of data that is collected/scraped …
=> renamed Metrics to MetricsState and move to a separate file

Dockerfile, Makefile, cloudbuild.yaml, pkg/epp/metrics/metrics.go, site-src/guides/metrics.md
The reference will be from `_PULL_BASE_REF` variable from the cloud build: https://docs.prow.k8s.io/docs/jobs/
The change also fixes the commit label by using the right variable added in https://github.com/kubernetes/test-infra/pull/34755/files.
=> feat: Add build reference to the info metrics

pkg/epp/common/config/defaults.go, pkg/epp/saturationdetector/config.go, pkg/epp/saturationdetector/saturationdetector.go, pkg/epp/saturationdetector/saturationdetector_test.go, pkg/epp/scheduling/config/config.go
This commit adds a new `SaturationDetector` component responsible for determining if backend model servers are saturated. It bases its decision on observed metrics like queue depth and KV cache utilization, using configurable thresholds.
To be submitted before #805 (split this change out for easier review).
Related  to: #674
It's initial implementation uses identical thresholds to the `HasCapacity` filter embedded in the default Scheduler filter chain for sheddable requests.
The detector is designed to be a self-contained unit that can be leveraged by other components for admission control and capacity assessment. This is the first step in a larger refactoring to externalize and centralize saturation detection logic.
=> Introduce SaturationDetector component

pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/util/request/body.go, pkg/epp/util/request/body_test.go
Resolves https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/790.
This PR introduces a utility function called `ExtractPromptFromRequestBody`. As its name suggests, it can extract the request prompt from the request body. For the `/chat/completions` API, it reads the messages field of the request and converts it into a prompt string. The conversion process simply uses `<|im_start|>` and `<|im_end|>` from the OpenAI ChatML format to denote the start and end of each message, thereby delimiting the list of conversation messages within the prompt.
`ExtractPromptFromRequestBody` is used by EPP when processing the request body to attempt to extract the prompt.
=> support extracting prompt from chat completions API

pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/backend/metrics/pod_metrics_test.go, pkg/epp/backend/metrics/types.go
This PR addresses flakiness observed in the TestMetricsRefresh test within the pkg/epp/backend/metrics package.
The root cause of the flakiness was a race condition stemming from the asynchronous nature of the `StopRefreshLoop` method. The test would:
1. Signal the metrics refresh goroutine to stop via `StopRefreshLoop()`.
2. Immediately update the mock `PodMetricsClient` to return different metric values.
3. Assert that the `PodMetrics` instance still held the original metrics.
Occasionally, the refresh goroutine would execute one final time after `StopRefreshLoop()` was called but before it fully terminated, picking up the new metrics. This led to the assertion failing.
To resolve this, I added a `time.Sleep(pmf.refreshMetricsInterval * 2 /* small buffer for robustness */)` before any …
=> Fix Test Flakiness by adding short sleep in TestMetricsRefresh

docs/proposals/006-scheduler/README.md
This sets down basic design principles of the current gateway scheduler. We also highlight who we are targeting as users, and why we prioritize the current approach. It also selects standard terminology for scheduling that the implementation should adopt.
This is a high level design and thus sets general scope, without expecting to fully address all problems.
=> Scheduler subsystem high level design proposal

pkg/epp/scheduling/plugins/prefix/plugin.go
default log level of epp is 4, having this log in debug level bombs the log with this line.
when running scheduler with prefix plugin enabled the log includes multiple lines of `found cached servers`.
this is running for every prefix and every server that includes that prefix.
the below log is a small part of a SINGLE REQUEST log:
```
{"level":"Level(-4)","ts":"2025-05-15T18:30:36Z","caller":"scheduling/scheduler.go:139","msg":"Running pre-schedule plugin","x-request-id":"97307923-8d96-4eaf-840d-3cb1c735f465","request":"TargetModel: meta-llama/Llama-3.1-70B-Instruct, Critical: true, PromptLength: 6803, Headers: map[:authority:inference-gateway :method:POST :path:/v1/chat/completions :scheme:http accept:application/json accept-encoding:gzip, deflate authorization:Bearer EMPTY …
```
=> reduce log level of "prefix cached servers" to TRACE

pkg/epp/scheduling/scheduler.go
fix the 'unsupported type: map[types.Pod]float64"}' error at the end of the log line:
```
{"level":"Level(-4)","ts":"2025-05-15T16:43:38Z","caller":"scheduling/scheduler.go:199","msg":"Before running picker plugin","x-request-id":"...","request":"TargetModel: meta-llama/Llama-3.2-3B-Instruct, Critical: false, PromptLength: 388, Headers: map[...]","podsError":"json: unsupported type: map[types.Pod]float64"}
```
=> fixed log before picker

pkg/epp/scheduling/plugins/filter/decision_tree_filter.go, pkg/epp/scheduling/plugins/filter/least_kvcache_filter.go, pkg/epp/scheduling/plugins/filter/least_queue_filter.go, pkg/epp/scheduling/plugins/filter/lora_affinity_filter.go, pkg/epp/scheduling/plugins/filter/low_queue_filter.go, pkg/epp/scheduling/plugins/filter/sheddable_capacity_filter.go, pkg/epp/scheduling/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/plugins/picker/max_score_picker.go, pkg/epp/scheduling/plugins/picker/random_picker.go
This PR updates godoc on all filters, pickers and prefix plugin (mutli-extension plugin).
there are few more places to add godoc but to avoid conflicts with other opened PR, this will be done in a follow up PR after the existing ones are merged.
=> updated godoc on scheduler filters, pickers and prefix plugin

pkg/epp/handlers/server.go, pkg/epp/server/runserver.go, test/integration/epp/hermetic_test.go
When requests/responses are not valid json, EPP clobbered any body message. This should improve UX & useful messaging in the face of failures.
=> adding logging & support for better Client response 

pkg/epp/handlers/server.go, pkg/epp/handlers/server_test.go
Ground work for: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/854
=> Adding util func for splitting large bodies into chunks

pkg/epp/metrics/metrics_test.go, pkg/epp/metrics/testdata/scheduler_plugin_processing_latencies_metric, pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, pkg/epp/scheduling/framework/scheduler_profile.go, pkg/epp/scheduling/framework/scheduler_profile_test.go
as discussed in scheduler design latest discussions, the plan is to completely remove the Pre/Post Cycle (previously called Pre/Post Schedule) from Scheduler. atm the only plugin that uses both is Prefix.
This PR completely removes `PreCycle` plugin from the scheduler.
As a side effect, this PR also fixes the following bug:
before this PR, the logic that calculated hashes in Prefix plugin `PreCycle` could have been buggy, since pods that have the longest prefix may be filtered out in the filter phase.
This PR is fixing this problem by calculating longest prefix only for the pods that passed the filtering phase.
cc: @ahg-g @kfswain @liu-cong
=> remove the PreCycle plugin from scheduler

site-src/guides/index.md
Following the instruction ["Istio > 5. Label the gateway"](https://deploy-preview-898--gateway-api-inference-extension.netlify.app/guides/#__tabbed_3_2), I got the following error. This PR updates the Istio gateway name for consistency.
```
$ kubectl label gateway llm-gateway istio.io/enable-inference-extproc=true
Error from server (NotFound): gateways.gateway.networking.k8s.io "llm-gateway" not found
```
=> docs: update Istio gateway name for consistency

hack/test-e2e.sh
Updates the `test-e2e.sh` script to use the correct Gateway listener ([xref](https://github.com/kubernetes-sigs/gateway-api-inference-extension/tree/v0.3.0/config/manifests/gateway)).
Fixes #899
=> Tools: Fixes test-e2e.sh script

docs/proposals/004-endpoint-picker-protocol/README.md
Part of https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/414
1. This PR extend value format of `x-gateway-destination-endpoint` to support multiple endpoints.
2. The new format could support mutliple fallback endpoints.
3. **The new format is compatible with previous format becase the previous format could be treat a speical case of new format.**
4. This will simplify the proxy implementation. The proxy needn't to handle different endpoint sources.
5. This will simplify the EPP implementation because the EPP needn't to set different endpoint sources.
6. It's possible to specify the fallback endpoints by HTTP header now.
=> Amend the endpoint picker protocol to support multiple fallback endpoints

site-src/guides/index.md
Resolves https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/896
This PR updates the Cleanup section for Istio in Getting Started.  I attached the logs when I executed the commands with my cluster.
<details><summary>Details</summary>
```
$ ./istioctl uninstall -y --purge
All Istio resources will be pruned from the cluster
Removed apps/v1, Kind=Deployment/istio-ingressgateway.istio-system.
Removed apps/v1, Kind=Deployment/istiod.istio-system.
Removed /v1, Kind=Service/istiod.istio-system.
Removed /v1, Kind=ConfigMap/istio.istio-system.
Removed /v1, Kind=ConfigMap/istio-sidecar-injector.istio-system.
Removed /v1, Kind=Pod/istio-ingressgateway-7d467856b8-7rzvt.istio-system.
Removed /v1, Kind=Pod/istiod-66b6b78b68-j8fc4.istio-system.
Removed /v1, …
```
=> Update the Cleanup section for Istio in Getting Started

cmd/epp/main.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/saturationdetector/saturationdetector.go, pkg/epp/saturationdetector/saturationdetector_test.go, pkg/epp/server/runserver.go, test/integration/epp/hermetic_test.go
This commit refactors the request processing pipeline, externalizing saturation detection and criticality-based service differentiation from the Scheduler. These responsibilities are now primarily managed by the RequestControl.Director.
This change is a preparatory step for the introduction of a new Flow Controller component, which will eventually absorb these admission control duties.
Diff base is: #808 (split out for easier reviewing)
Related to: #674
Key changes include:
- Introduced `PreDispatch` method to `RequestControl.Director`. It utilizes the `SaturationDetector` for admission control of non-critical requests and handles request criticality to determine if saturation checks are bypassed.
- The saturation detection logic for dropping non-critical requests is intentionally …
=> Refactor: Externalize Scheduler's saturation logic and criticality-based service differentiation

Makefile, config/manifests/vllm/sim-deployment.yaml, site-src/guides/index.md, test/e2e/epp/README.md
- Adds vLLM Simulator (vllm-sim) as a supported backend model server
- Updates the Makefile to use vllm-sim as the default backend
- Updates the quickstart to provide vllm-sim as a model server deployment option.
```sh
$ make test-e2e
MANIFEST_PATH=/home/solo-system-dhansen/gateway-api-inference-extension/config/manifests/vllm/sim-deployment.yaml go test ./test/e2e/epp/ -v -ginkgo.v
=== RUN   TestAPIs
...
Ran 1 of 1 Specs in 20.623 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
```
Fixes #897
=> Adds vLLM Simulator Support

Makefile
This PR fixes a typo that was introduced in #880 which added `verify` target twice in Makefile.
=> fixed typo in makefile

cmd/epp/main.go, pkg/epp/util/env/env.go, pkg/epp/util/env/env_test.go
This PR switches to read boolean env vars instead of reading string and compare to "true".
in unit-tests, removed the `value` field. value is always set by the setup function and therefore `value` field is redundant.
cc'ing @LukeAVanDrie which I know was working on this area.
=> added GetEnvBool function and unit-tests

cmd/epp/main.go, pkg/epp/handlers/server.go, pkg/epp/metrics/metrics.go, pkg/epp/plugins/plugins.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/requestcontrol/plugins.go, pkg/epp/requestcontrol/types.go, pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/scheduler_profile.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go, pkg/epp/server/runserver.go, test/integration/epp/hermetic_test.go
This PR moves PostResponse plugins out of scheduler and into requestcontrol layer (more specifically into the director).
several code changes were done as part of this change:
- moved the creation of director to `main.go` in order to allow easy setup of plugins as we have with scheduler. a plugin should be able to register to both scheduler plugin and post response plugin in main.
- added PostResponsePlugins slice in director and added the `WithPostResponsePlugins` function to allow easy setup of the PostResponsePlugins.
- PostResponse plugin now gets both the request and the response - this is very useful in prefix plugin in order to be able to concat the prompt with the response and save in prefix cache.
- unit + integration tests were updated accordingly.
- example how to register …
=> move PostResponse plugins to requestcontrol instead of scheduler

pkg/epp/requestcontrol/director.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go
after the merge of #910, this field is no longer used by the scheduler or any of its plugins.
=> remove Critical boolean from scheduling request

pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/plugins/profile-picker/all_profiles_picker.go, pkg/epp/scheduling/scheduler.go
since this is a custom logic, getting context as argument can be useful. 
specific in my case I want to use contextual logging.
This was missed from the initial version that was merged.
=> added context argument to scheduling profile picker

site-src/contributing/index.md
Fixes the meeting recording link so the text is properly rendered instead of:
=> Docs: Fixes Meeting Recording Link

site-src/guides/serve-multiple-genai-models.md
- clarify the use of BBR upfront (and not only as comment in YAML), and dispatching to different InferencePool/EPP
- fix typo in sample inference requests - both requests were sent to same model
=> Changes to multi-model guide in documentation

cmd/epp/main.go, conformance/testing-epp/scheduler.go, conformance/testing-epp/sheduler_test.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go, pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go, pkg/epp/scheduling/framework/scheduler_profile.go, pkg/epp/scheduling/framework/scheduler_profile_test.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_config.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go
following agreements made on #905, 
this PR implements another step towards the end goal of the scheduler new design. main changes include:
- rename of the profile handling plugin to ProfileHandler and add the ProcessProfilesResults extension point (function called ProcessResults in ProfileHandler interface, as agreed in the design discussion).
- add SchedulingResult which includes the map of the profile runs results and the key of the primary profile that is used in the director code to set the destination header (in the future it can be changed to use a `PreRequest` plugin).
- add the ProcessResults call in the scheduler request flow.
- create CycleState per request and not per profile.
- add a DEPRECATED comment on `PostCycle`. once PostResponse is used in prefix plugin, we should …
=> scheduler redesign continuation

site-src/guides/metrics.md
TESTED=preview with local mkdocs
fix https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/955
=> fix: Mark alert block as yaml to fix syntax error

site-src/guides/index.md
=> Bump Istio tag reference

api/v1alpha2/inferencepool_types.go
Updates godocs for InferencePool `ExtensionReference` field to include expected 5xx response code for invalid EPP references.
xref: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/959/files#r2145990979
=> API: Adds 5xx Status Code for Invalid ExtRef

cmd/epp/main.go, cmd/epp/runner/runner.go
This PR moves context creation to `main.go` rather than internally in `runner`. 
this is useful when writing a different main like llm-d, 
allowing to propagate the same context to the whole system.
=> moved the creation of the context to main.go.

cmd/epp/runner/runner.go, pkg/epp/server/runserver.go, test/testdata/envoy.yaml, test/testdata/inferencepool-e2e.yaml
Add health checking  for Upstram: epp.
Fix #240
=> feat: add health check for epp cluster

pkg/epp/server/server_test.go, test/utils/server.go
Added unit tests for the EPP gRPC streaming server. 
In particular, this test tests the streaming server's processing of the various Envoy gRPC messages. An in-memory buffered listener is used for the gRPC server, thus eliminating the need to find free ports in the test system. The code has been structured with several helper functions, that should make it easier in the future to add more tests of this nature. In particular, this should enable end-to-end tests without the need to find free ports.
This test uses a dummy director to choose the target pod. The goal here was to test the streaming server, to setup infrastructure for more similar tests, and not necessarily test the director or the scheduler.
=> test: gRPC server unit tests and utilities for further end-to-end tests

site-src/guides/metrics.md, tools/dynamic-lora-sidecar/README.md, tools/dynamic-lora-sidecar/deployment.yaml, tools/dynamic-lora-sidecar/requirements.txt, tools/dynamic-lora-sidecar/sidecar/sidecar.py, tools/dynamic-lora-sidecar/sidecar/test_sidecar.py
Resolves https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/600
Update dynamic-lora-sidecar to expose metrics to track loaded adapters. `lora_syncer_adapter_status`  is a binary metric with the adapter_name label. I confirmed sidecar.py ran  an HTTP server with the port 8080 that returned metrics.
<details><summary>curl http://localhost:8080/metrics</summary>
* Run sidecar.py
```
(venv) laborant@dev-machine:sidecar$ pwd
/home/laborant/gateway-api-inference-extension/tools/dynamic-lora-sidecar/sidecar
(venv) laborant@dev-machine:sidecar$ uv run --with-requirements ../requirements.txt python sidecar.py --config ../configmap.yaml
2025-06-13 04:59:09 - INFO - sidecar.py:118 -  Settings initialized: health check timeout=300s, interval=2s, reconcile trigger=5s
2025-06-13 …
```
=> Update dynamic-lora-sidecar to expose metrics to track loaded adapters

pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/plugins.go, pkg/epp/requestcontrol/request_control_config.go
This PR adds the `PreRequest` extension point to requestcontrol layer.
the registered `PreRequest` plugins will be invoked after a successful result was received from the scheduling layer (that is, a successful SchedulingResult). the extension allows wiring up multi profile results using the request properties (e.g., Headers that will be later added to the request using the `generateHeaders` helper func).
More specifically, this is the enabler for clean coding of the Prefill/Decode wiring in llm-d.
=> adding pre-request plugin to requestcontrol layer

conformance/conformance.go
-namespace-labels key=value,k=v
-namespace-annotations key=value,k=v
=> fix(Conformance): Add namespace-(labels|annotations) flag parsing

.github/ISSUE_TEMPLATE/new-release.md, hack/release-quickstart.sh
- ``hack/release-quickstart.sh``: Adds support for managing the image tag and pull policy for vLLM CPU and Simulator manifests. Updates the sed commands for BSD `sed` on MacOS (does not accept the space before the `{`, nor will it parse the closing brace as part of the address block).
- `.github/ISSUE_TEMPLATE/new-release.md`: Updates docs
Fixes #1017
=> Adds vLLM CPU and Sim Support to Release Script

tools/dynamic-lora-sidecar/Dockerfile, tools/dynamic-lora-sidecar/Makefile, tools/dynamic-lora-sidecar/README.md
Part of https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/987
Add Makefile to run unit tests of tools/dynamic-lora-sidecar locally. I plan to use it for a CI job.
=> Add Makefile to run unit tests of tools/dynamic-lora-sidecar locally

pkg/epp/common/config/configloader_test.go, pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go, pkg/epp/scheduling/scheduler.go
This PR make minor change to scheduler and ProfileHandler and delegates the decision on whether the Schedule call should fail or not when a single profile run fails.
more background about this PR:
in llm-d we have two configured profiles - Prefill and Decode. 
if decode profile fails, we would like to fail the request. on the other hand, if prefill profile run fails, we would like to serve the request by decode only. this could happen if there is no available prefill pod at the time the request is sent.
More generally, since profiles and plugins are extensible and pluggable, it makes sense to delegate the decision on whether failing profile should fail the whole request or not to ProcessResults.
in the case where profile fails, it's profile result will be nil.
=> profile handler ProcessResult returns additional return value

pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go
Fixes: #1001 
This PR makes the InferenceModel an optional CRD. If no match is found, the matched model is set to the lowest criticality.
Currently this is hard-coded just to unblock: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1001
Future PRs will allow for configuration of the default (implemented with the implementation of `InferenceSchedulingObjective`: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1007
=> Making inferenceModel optional

mkdocs.yml, site-src/concepts/design-principles.md
As the project continues to grow, it would be helpful to have some high level design principles for the project. These principles can help guide us when determining which features and work to prioritize.
/cc @ahg-g @smarterclayton @danehans @kfswain @Jeffwan @shaneutt
=> Adding Design Principles

.github/ISSUE_TEMPLATE/new-release.md, hack/release-quickstart.sh
Backport of PR #1020- Adds vLLM CPU and Sim support to the release tooling and docs.
Supercedes https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1025
=> Backport: PR 1020- Adds vLLM CPU and Sim Support to Release Script

api/v1alpha2/inferencepool_types.go, config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
Adds default status condition to the InferencePool API.
Fixes #825
=> API: Adds default status condition to InferencePool

config/manifests/vllm/sim-deployment.yaml
this fix is part of #1022. tested locally and it works.
reference to sim docker registry with `latest` tag [here](https://github.com/llm-d/llm-d-inference-sim/pkgs/container/llm-d-inference-sim).
cc @danehans
=> update sim deployment tag to latest

cmd/epp/runner/register.go, conformance/testing-epp/plugins/filter/request_header_based_filter.go, docs/proposals/0845-scheduler-architecture-proposal/interfaces/interface.go, pkg/epp/common/config/configloader_test.go, pkg/epp/plugins/plugins.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go, pkg/epp/scheduling/framework/plugins/filter/filter_test.go, pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go, pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go, pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go, pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go, pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go, pkg/epp/scheduling/framework/plugins/scorer/kvcache.go, pkg/epp/scheduling/framework/plugins/scorer/queue.go, pkg/epp/scheduling/framework/scheduler_profile.go, pkg/epp/scheduling/framework/scheduler_profile_test.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_config_test.go
Following up on #1008, this replace Name() with Type() everywhere (incl. constants and fields names).
A follow up would reintroduce Name() (which can be assigned or auto-generated when unspecified [^1]) and then, depending on context, use Type(), Name() or both when plugin information is logged is loaded from config.
@ahg-g @kfswain @nirrozenbaum - please let me know if you prefer a single PR or two for the complete change.
[^1]: in the case of configuration, names must be provided or made consistent (e.g., default to Type()) so they can be used  with well known reference name. For other cases a random generated name (`<type>-xxxxx`) would be used.
=> refactor: rename plugin.Name() => plugin.Type()

site-src/guides/index.md
Update the Getting Started guide to use the latest CRDs - https://github.com/kubernetes-sigs/gateway-api-inference-extension/releases/latest/download/manifests.yaml
(no need to update the doc for every version)
=> docs: update the Getting Started guide to use the latest CRDs

conformance/testing-epp/plugins/filter/filter_test.go, conformance/testing-epp/plugins/filter/request_header_based_filter.go, pkg/epp/common/config/configloader_test.go, pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go, pkg/epp/scheduling/framework/plugins/filter/filter_test.go, pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go, pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go, pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go, pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go, pkg/epp/scheduling/framework/plugins/scorer/kvcache.go, pkg/epp/scheduling/framework/plugins/scorer/kvcache_test.go, pkg/epp/scheduling/framework/plugins/scorer/queue.go, pkg/epp/scheduling/framework/plugins/scorer/queue_test.go, pkg/epp/scheduling/framework/scheduler_profile.go, pkg/epp/scheduling/framework/scheduler_profile_test.go, pkg/epp/scheduling/scheduler.go
This PR adds CycleState arg to `Pick` and `ProcessResults` functions of `ProfileHandler`.
Additional minor change is being consistent in arguments order across all scheduling plugins. 
after this PR all plugins receive first args (context, cycle-state) and then the plugin specific args like request, etc.
This was raised by @kfirtoledo while working on PD scorer, and had the requirement to access some of the scorer calculations in ProcessResults (need to communicate it through CycleState).
NO LOGIC CHANGE.
=> added cycle state to pick & process results in profile handler

conformance/tests/basic/inferencepool_httproute_port_validation.go, conformance/tests/basic/inferencepool_httproute_port_validation.yaml
The test was auto-merged #911 before the common resources is merged. So added it back
Tested
1. istio
```
--- PASS: TestConformance (6.50s)
--- SKIP: TestConformance/HTTPRouteInvalidInferencePoolRef (0.00s)
--- SKIP: TestConformance/InferencePoolAccepted (0.00s)
--- PASS: TestConformance/InferencePoolHTTPRoutePortValidation (1.74s)
--- PASS: TestConformance/InferencePoolHTTPRoutePortValidation/Scenario_1:_HTTPRoute_backendRef_to_InferencePool_with_Port_Unspecified (1.07s)
--- PASS: TestConformance/InferencePoolHTTPRoutePortValidation/Scenario_2:_HTTPRoute_backendRef_to_InferencePool_with_Port_Specified_and_Matching (0.06s)
--- PASS: TestConformance/InferencePoolHTTPRoutePortValidation/Scenario_3:_HTTPRoute_backendRef_to_InferencePool_with_Port_Specified_and_Non-Matching._Request_still_pass …
```
=> refactor(confromance) use common resources for `InferencePoolHTTPRoutePortValidation` test

api/config/v1alpha1/defaults.go, api/config/v1alpha1/endpointpickerconfig_types.go, conformance/testing-epp/plugins/filter/request_header_based_filter.go, pkg/epp/common/config/loader/configloader.go, pkg/epp/common/config/loader/configloader_test.go, pkg/epp/plugins/plugins.go, pkg/epp/plugins/registry.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go, pkg/epp/scheduling/framework/plugins/filter/filter_test.go, pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go, pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go, pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go, pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go, pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go, pkg/epp/scheduling/framework/plugins/scorer/kvcache.go, pkg/epp/scheduling/framework/plugins/scorer/queue.go, pkg/epp/scheduling/framework/scheduler_profile_test.go, test/testdata/configloader_1_test.yaml
This is a follow up to #1038.
Fixes #1008 
Plugin changes (cc: @ahg-g @kfswain @nirrozenbaum)
- Name() method to Plugin interface
- Name() implementation for all Plugin implementations
- Rename Factory function to FactoryFunc - similar to (e.g.,)  http.HandlerFunc (to differentiate from http.Handler *interface*)
EPP Configuration changes, see [1038 comment](https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1038#pullrequestreview-2948349467) (cc: @shmuelk @ahg-g)
- Refactor field name from PluginName to Type
- changes to config format to use `type` instead of `pluginName`
- (unrelated) added comments on configuration test cases (since some names could be misleading)
=> Reintroduce Plugin.Name() 

pkg/epp/flowcontrol/README.md, pkg/epp/flowcontrol/types/README.md, pkg/epp/flowcontrol/types/errors.go, pkg/epp/flowcontrol/types/flow.go, pkg/epp/flowcontrol/types/outcomes.go, pkg/epp/flowcontrol/types/request.go
This PR introduces the foundational building blocks for the new **Flow Control** system, designed to manage priority, fairness, and queuing for inference workloads.
The goal is to provide a sophisticated mechanism for managing diverse SLOs and preventing issues like Head-of-Line blocking and system overload, which are not addressed by simple FCFS temportal scheduling. This is a relatively sophisticated and complex system that will need to be split across several PRs. This initial submission lays the groundwork for the entire module by establishing its core concepts and data contracts (basically all types with no cross-package dependencies).
This work tracks issue #674
For historical context, the initial KEP-like proposal can be found …
=> feat(flowcontrol): Add Foundational Types and Architecture

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, pkg/epp/scheduling/types/cycle_state.go
The schedulingContextState type was renamed to SchedulingContextState to make it accessible from other packages and enable sharing of prefix state across different plugins.
=> refactor: Allow export prefix SchedulingContextState for use across plugins

cmd/epp/runner/register.go, cmd/epp/runner/runner.go, pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go, pkg/epp/scheduling/framework/plugins/filter/filter_test.go
This PR adds a factory function for the DecisionTree filter along with tests for the added factory function.
In addition there is a small refactoring in cmd/epp/runner/runner.go that was requested in PR #1039 
This PR fixes issue #1011
=> feat: Added a factory function for the DecisionTree filter

cmd/epp/runner/runner.go, mkdocs.yml, site-src/guides/metrics-and-observability.md
Adding pprof to the metrics endpoint and updating the documentation to support manual fetch of profiles.
Happy to add more documentation if needed.
=> Adding pprof endpoints to metrics port

conformance/tests/basic/epp_unavailable_fail_open.go, conformance/tests/basic/gateway_following_epp_routing.go, conformance/tests/basic/inferencepool_httproute_port_validation.go, conformance/tests/basic/inferencepool_multiple_rules_different_pools.go, conformance/tests/basic/inferencepool_resolvedrefs_condition.go, conformance/utils/kubernetes/helpers.go, conformance/utils/traffic/traffic.go
1. in `traffic.go`: merge `MakeRequestWithRequestParamAndExpectSuccess` and `MakeRequestAndExpectSuccess` resolving #983 .
* `MakeRequestWithRequestParamAndExpectSuccess` is accepting a `request` type parameter which allows putting request body and request body into it. It's a superset of original `MakeRequestAndExpectSuccess`
2. in `helpers.go`: merge `GetPodsWithLabel` and `GetPod` resolving #1003
3. also updated the `HTTPRouteMultipleRulesDifferentPools` to make sure it only tests the httpRoute is routing to different pods belonging different pools.
=> refactor(conformance) merge similar utility functions.

conformance/conformance.go
Currently we have to manually create a `gateway-conformance-web-backend` namespace, because it was considered useless and deleted in #982. However, it is actually needed when we run `suite.Setup`, it is checked [here](https://github.com/kubernetes-sigs/gateway-api/blob/v1.3.0/conformance/utils/suite/suite.go#L358) in the gateway-api library.
Checking the [`suite.Setup`](https://github.com/kubernetes-sigs/gateway-api/blob/v1.3.0/conformance/utils/suite/suite.go#L325) function, not all of them is needed by the conformance tests in inference gateway. So in this PR, I create a standalone function and just do not call the `suite.Setup`.
=> fix(conformance): fix conformance setup issue by not relying on `suite.Setup` from gateway-api

api/v1alpha2/inferencepool_types.go, docs/proposals/002-api-proposal/README.md
1.  **Clarified Status for Invalid `ExtensionReference`**
*   The specification is updated to explicitly state that when an `ExtensionReference` in an `InferencePool` points to an invalid `EndpointPicker` (EPP), the `ResolvedRefs` condition on the `InferencePool` must be set to `status: false`.
*   This makes the behavior unambiguous and aligns it with the conformance test implemented in #1061.
2.  **Expanded `InferencePoolReason` Values**
*   New `InferencePoolReasonHTTPRouteNotAccepted` value for inferencePoolReason have been added to provide more granular status information.
*   This change is inspired by the detailed reasons available for resources like [`HTTPRoute`](https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1/shared_types.go#L289-L395) in the Gateway API per …
=> API: Refine ResolvedRefs condition for invalid ExtensionReference and expand InferencePoolReason values

pkg/epp/util/error/error_test.go
/kind cleanup
This PR adds comprehensive unit tests for the `pkg/epp/util/error` package, which previously had no test coverage.
- Add comprehensive tests for Error.Error() method
- Add tests for CanonicalCode() function with edge cases
- Test all error code constants
- Cover 100% test coverage for pkg/epp/util/error
- All new tests pass
- Existing tests continue to pass
- 100% test coverage achieved for the package
=> test(epp): add unit tests for error package

pkg/epp/scheduling/framework/plugins/picker/picker_test.go
- Validates behavior of picker plugins under:
- Single highest-scoring pod
- Multiple pods with equal scores
- Empty input list
Fixes #1097
=> Add unit tests for picker plugin

pkg/epp/backend/metrics/logger.go, pkg/epp/metrics/metrics.go
Using upper case to be consistent with similar functions in the same file
=> Upper case `Inference` in `metrics.RecordInferencePoolReadyPods` for consistency

config/manifests/vllm/sim-deployment.yaml
a new version of llm-d simulator was just release (v0.2.0).
unfortunately, this release had some breaking changes and the e2e tests are now broken.
this PR is rolling back to use a specific sim version and not latest (the one that previously worked), as we don't want our ci tests to break on simulator release in case there are breaking changes. it would be better to update the version in a controlled manner until simulator releases and apis become more stable.
I've made the necessary changes to update the sim deployment to the latest v0.2.0 release and tested it but it wasn't working for me. we would need to further explore (in a different issue) the version update.
This PR is rolling back to the latest version that working before the sim release.
=> fixed sim deployment for e2e tests

pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go, pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
This PR adds a check to verify default configuration will be used if no parameters are defined in the config file.
please pay attention that picker plugins were not added in this PR since PR #1059 was updating pickers and as part of that update current change is covered for pickers in that PR.
=> verify fallback to default values if parameters are not defined in config file

cmd/epp/runner/runner.go, pkg/epp/common/config/loader/configloader.go, pkg/epp/common/config/loader/configloader_test.go
This PR does minor refactoring to config loading from file/text.
the following changes are included:
- when working with sets, the best practice in k8s is to use `"k8s.io/apimachinery/pkg/util/sets"`, which is backed by map[T]struct{}, but is more readable. updated config loader to use k8s sets.
- config loader doesn't get both text (as bytes) and file anymore. this should be handled in the caller and the config loader gets bytes after the caller converted the file or text into bytes. 
**generally speaking, I'm not sure we need to maintain the two options and using a filepath seems sufficient and more aligned with k8s (e.g., mounting configmap to file system). but this is open for discussion and **not part of this PR**.
- config loader gets as input the configBytes and the handle to add …
=> minor refactor to config loading from file/text

pkg/epp/plugins/typedname.go
=> minor updates to typed-name

cmd/epp/runner/runner.go, conformance/testing-epp/scheduler.go, conformance/testing-epp/scheduler_test.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, pkg/epp/scheduling/framework/plugins/picker/common.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/picker_test.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go, pkg/epp/scheduling/framework/scheduler_profile_test.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_test.go, pkg/epp/scheduling/types/types.go
This PR implements the multiple destination handling in the scheduling layer, as defined in the EPP protocol:
https://github.com/kubernetes-sigs/gateway-api-inference-extension/tree/main/docs/proposals/004-endpoint-picker-protocol#destination-endpoint
please pay attention that this PR updates only the scheduling layer. 
as a follow up, we should update the request-control layer and the handlers to use the multiple returned endpoints according to the protocol.
In order to keep this PR tightly scoped, the director keeps using a single targetPod to keep the current functionality.
=> handle picking multiple destinations in scheduling layer

api/v1alpha2/inferencepool_types.go
This is intended to clarify the default expectation of using TLS when Gateways are connecting to Endpoint Picker(s). This matches the default mode of Endpoint Picker. While it leaves room for configuration of plain-text or other protocols altogether, I think it's sensible for the default behavior here to rely on TLS.
Thanks to @aslakknutsen for raising this as he was reviewing conformance tests earlier. Our conformance tests made this assumption of default behavior without any corresponding guidance in the API spec. This PR intends to resolve that.
/cc @danehans @LiorLieberman @aslakknutsen @zetxqx
=> Clarify that connections to EPP should use TLS by default

conformance/tests/basic/inferencepool_invalid_epp_service.go
Currently when the EPP does not exist, the test case is also checking if the httpRoute is resolvedDefs to true. However, this is not specified in the API spec. Also, showing resolvedDefs to false on httpRoute is more user-friendly as well. 
the following is the condition status of httpRoute on my dev environment for gke-l7
```
Status:
Parents:
Conditions:
Last Transition Time:  2025-07-09T18:01:13Z
Message:               error cause: reference-not-found: Error GWCER104: HTTPRoute "gateway-conformance-app-backend/httproute-for-invalid-epp-pool" is misconfigured, err: failed to validate inference pool extension ref: InferencePool extension service non-existent-epp-svc not found.
Observed Generation:   1
Reason:                BackendNotFound
Status:                False
Type: …
```
=> feat(conformance): loose the InferencePoolInvalidEPPService to only check httpRoute is accepted true.

Makefile
```
(base) ➜  gateway-api-inference-extension git:(main) make test-integration
bash: line 1: /Users/kiki/workspace/golang/src/sigs.k8s.io/gateway-api-inference-extension/bin/setup-envtest: No such file or directory
CGO_ENABLED=1 KUBEBUILDER_ASSETS="" go test ./test/integration/epp/... -race -coverprofile cover.out
ld: warning: '/private/var/folders/n6/33y75ytn36g38k2wnkb6lp8r0000gn/T/go-link-1877484310/000013.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
2025-07-11T16:52:58+08:00	ERROR	logging/fatal.go:29	Failed to start test environment	{"config": "<nil>", "error": "unable to start control plane itself: failed to start the controlplane. retried 5 times: unable to run command \"kube-apiserver\" to …
```
=> Fix makefile: test-integration

cmd/epp/runner/runner.go, config/charts/inferencepool/templates/epp-deployment.yaml, config/charts/inferencepool/values.yaml, pkg/epp/server/runserver.go
Also adding helm config so the tooling can be adjusted from a helm command.
=> adds flag to disble pprof if desired, defaulted on

cmd/epp/runner/runner.go, pkg/epp/scheduling/scheduler.go, pkg/epp/scheduling/scheduler_test.go, test/integration/epp/hermetic_test.go
This PR removes the NewScheduler function and all its usage in the code.
Instead, in order to create scheduler one should use NewSchedulerWithConfig.
This PR is built on top of  #1151 and #1152 and therefore should be merged only after them.
once that is done, I will rebase this one.
/hold to make sure other PRs are reviewed and merged first.
this PR completes the work required by #1130.
fix #1130 
cc @ahg-g @kfswain
=> remove NewScheduler function

conformance/resources/manifests/manifests.yaml, test/testdata/inferencepool-e2e.yaml
this flag is no longer used (was removed from main)
=> removed USE_STREAMING env var from conformance + tests

pkg/epp/flowcontrol/framework/doc.go, pkg/epp/flowcontrol/framework/mocks/mocks.go, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/README.md, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/factory.go, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/fcfs/fcfs.go, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/fcfs/fcfs_test.go, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/functional_test.go, pkg/epp/flowcontrol/framework/plugins/queue/README.md, pkg/epp/flowcontrol/framework/plugins/queue/factory.go, pkg/epp/flowcontrol/framework/plugins/queue/functional_test.go, pkg/epp/flowcontrol/framework/policies.go, pkg/epp/flowcontrol/framework/queue.go
This PR is part of a stack.
1. **PR #1138:** Pluggable queues
2. **This PR:** Pluggable intra flow dispatch policies
**Incremental diff against #1138:** https://github.com/LukeAVanDrie/gateway-api-inference-extension/compare/feat/flow-control-framework-plugins-queue...feat/flow-control-frameowrk-plugins-intra-flow-dispatch
This work tracks #674 
This PR introduces the second major component of the new pluggable flow control system: the **Intra-Flow Dispatch Policy framework**.
While the previous PR introduced the `SafeQueue` framework for managing the *storage* of requests, this PR introduces the `IntraFlowDispatchPolicy` framework for managing the *logic* of request selection. It is responsible for **temporal scheduling**: determining the order in which requests are selected for dispatch …
=> feat: Introduce pluggable intra-flow dispatch policy framework

site-src/guides/index.md
/cc @kfswain @danehans @nirrozenbaum
=> Update istio release

pkg/epp/flowcontrol/README.md, pkg/epp/flowcontrol/contracts/registry.go, pkg/epp/flowcontrol/framework/errors.go, pkg/epp/flowcontrol/framework/mocks/mocks.go, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/README.md, pkg/epp/flowcontrol/framework/plugins/queue/README.md, pkg/epp/flowcontrol/framework/plugins/queue/benchmark_test.go, pkg/epp/flowcontrol/framework/plugins/queue/factory.go, pkg/epp/flowcontrol/framework/plugins/queue/functional_test.go, pkg/epp/flowcontrol/framework/plugins/queue/listqueue/listqueue.go, pkg/epp/flowcontrol/framework/plugins/queue/maxminheap/maxminheap.go, pkg/epp/flowcontrol/framework/plugins/queue/maxminheap/maxminheap_test.go, pkg/epp/flowcontrol/framework/policies.go, pkg/epp/flowcontrol/framework/queue.go, pkg/epp/flowcontrol/registry/managedqueue.go, pkg/epp/flowcontrol/registry/managedqueue_test.go, pkg/epp/flowcontrol/types/flow.go, pkg/epp/flowcontrol/types/request.go
This work tracks #674 
This PR introduces the foundational layer for the Flow Registry, which will act as the stateful control plane for managing queues and policies. It establishes the core service `contracts` for the system and provides the `ManagedQueue`, a stateful decorator that wraps queue plugins.
This work is a prerequisite for the full `FlowRegistry` implementation.
1.  **`ports` -> `contracts` Rename**: The `ports` package has been renamed to `contracts` to more accurately reflect its purpose in defining the service interfaces for our "Ports and Adapters" architecture. This avoids potential confusion with network-related "ports" in the Kubernetes ecosystem.
2.  **`ManagedQueue` Decorator**: A new `registry.managedQueue` component is introduced. It follows the decorator pattern, …
=> feat(flowcontrol): Introduce ManagedQueue and Service Contracts

config/manifests/vllm/cpu-deployment.yaml
Fixes: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1022
=> chore: update vllm deployment tag to latest

site-src/guides/implementers.md
This PR adds a section to the implementers guide with an outline for implementing compatible data planes that conform to the Endpoint Picker protocol.
/cc @robscott
=> Add an "Implementing a Compatible Data Plane" section to the implementers guide

pkg/epp/server/runserver.go, site-src/guides/epp-configuration/config-text.md, site-src/guides/index.md, site-src/guides/inferencepool-rollout.md, site-src/implementations/model-servers.md
Flags changed to kebab-case from https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1177, this Pull Request updates all the un-changed / lost track documentations to align the flags.
=> docs: update to use kebab-cased flags changed at #1177

cmd/epp/runner/runner.go
This PR fixes segmentation fault that may happen if the scheduler config is not initialized.
in GIE we allow configuring plugins either through config api or through code.
therefore when the config flags are missing, the program doesn't exit (to allow configuration by code to work).
we should add a nil check to validate we don't get segmentation fault when trying to initialize the scheduler.
this issue was originally hit in llm-d-scheduler, and reported here:
https://github.com/llm-d/llm-d-inference-scheduler/issues/255
=> added graceful shutdown when scheduler config is not initialized

.github/ISSUE_TEMPLATE/new-release.md, config/manifests/vllm/sim-deployment.yaml, hack/release-quickstart.sh
As the title suggests, we use the v0.3.0(latest) sim image to take advantage of the latest features. 
For example, the size of the mirror image, etc. (121MB -> 37.2MB)
=> chore: 🔨 Use the v0.3.0 llm-d-inference-sim image tag.

.github/ISSUE_TEMPLATE/new-release.md
while working on release v0.5 I noticed the tags are Unverified.
when following the release issue, there are some commands that include that -s for signoff (in the commit section).
added the -s for the tag section to have verified tags.
cc @kfswain @danehans
=> release issue template: updated the tag command to include the -s for signing the tag

config/manifests/inferencepool-resources.yaml
Follow up of https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1213
=> fix: missing permission to list inference.networking.k8s.io/v1/inferencepool

pkg/epp/flowcontrol/contracts/mocks/mocks.go, pkg/epp/flowcontrol/contracts/saturationdetector.go, pkg/epp/flowcontrol/controller/doc.go, pkg/epp/flowcontrol/controller/internal/doc.go, pkg/epp/flowcontrol/controller/internal/filter.go, pkg/epp/flowcontrol/controller/internal/filter_test.go, pkg/epp/flowcontrol/controller/internal/item.go, pkg/epp/flowcontrol/controller/internal/item_test.go, pkg/epp/flowcontrol/controller/internal/processor.go, pkg/epp/flowcontrol/controller/internal/processor_test.go, pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/besthead/besthead_test.go
This pull request introduces the `ShardProcessor`, the core data plane engine of the `FlowController`. This is the heart of the flow control system, making it capable of processing, queuing, and dispatching requests.
This PR is part of a stack.
1. **PR #1202 :** Behavioral mocking
2. **This PR:** Implement `ShardProcessor`
**Incremental diff against #1202:** https://github.com/LukeAVanDrie/gateway-api-inference-extension/compare/refactor/flow-control-mocks...feat/flow-control-controller-shard-processor
Each `ShardProcessor` is paired one-to-one with a `contracts.RegistryShard` and is responsible for all request lifecycle operations on that shard. It acts as the concurrent worker that executes against the state provided by the shard, orchestrating policies and managing requests from …
=> feat(flowcontrol): Implement ShardProcessor engine 

docs/proposals/1199-inferencemodel-api-evolution/README.md
Please consider : https://docs.google.com/document/d/1x6aI9pbTF5oOsaEQYc9n4pBBY3_AuEY2X51VKxmBSnU/edit?tab=t.0#heading=h.towq7jyczzgo & https://docs.google.com/document/d/1G-CQ17CM4j1vNE3T6u9uP2q-m6jK14ANPCwTfJ2qLS4/edit?tab=t.0 required prior reading.
=> Proposing the successor to the InferenceModel API

config/crd/bases/inference.networking.k8s.io_inferencepools.yaml, config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml, config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml, version/version.go
Update the CRD bundleVersion to main-dev for the main branch. Run the make generate to update the CRD's annotation in the main branch.
This should be merged after https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1214.
=> chore: update CRD BundleVersion to main-dev

pkg/epp/plugins/typedname.go
Since `Plugin` returns a `TypedName` by value the `String()` method with pointer receiver was not called. 
Go happily calls the value receiver based methods for pointers as well.
This was causing logs to print `{<type> <name>}` (default string representation) instead of the expected output of String() (`<name>/<type>`).
=> Change String() to accept a value reciever.

site-src/performance/regression-testing/index.md
This pull request updates the regression testing documentation to enhance clarity, improve formatting, and introduce a new section on nightly benchmarking. The most important changes include reformatting test case descriptions, adding details about traffic distribution and metrics expectations, and documenting the nightly benchmarking process.
* **Reformatted Test Case Details**: Improved readability for test cases by using clearer formatting, such as bullet points and percentages for traffic distribution in the multi-LoRA test case. Updated terminology for request rates (`QPS`) and added clarity to dataset descriptions.
* **Enhanced Metrics Expectations**: Clarified expectations for regression analysis metrics, including R² values for prompts and latency, with minor variance allowances. …
=> Add nightly benchmarking documentation

config/charts/inferencepool/templates/rbac.yaml, config/manifests/inferencepool-resources.yaml, test/e2e/epp/e2e_suite_test.go, test/testdata/inferencepool-e2e.yaml, test/utils/utils.go
Fixes #224
Testing:
```
helm upgrade -i epp ./config/charts/inferencepool
curl 10.0.227.159/v1/models
{"object":"list","data":[{"id":"...
```
```release-note
Split EPP RBAC into cluster and namespaced scoped permission
```
=> fix: split EPP RBAC into cluster and namespaced scoped permission

cmd/epp/runner/runner.go, pkg/epp/scheduling/framework/plugins/scorer/lora_affinity.go, pkg/epp/scheduling/framework/plugins/scorer/lora_affinity_test.go, site-src/guides/epp-configuration/config-text.md
#967 
Changes: Added new scorer for v2 scheduler.
Benchmark details:
Coefficient of Determination (R^2) between before and after runs:
avg_normalized_time_per_output_token_ms R^2 = 0.9887
p90_per_token_latency_ms       R^2 = 0.9691
p90_latency_ms                 R^2 = 0.9633
num_prompts_attempted          R^2 = 1.0000
num_prompts_succeeded          R^2 = 0.9951
=> Update lora affinity to be a scorer.

conformance/conformance.go, conformance/tests/epp_unavailable_fail_open.go, conformance/tests/httproute_invalid_inferencepool_ref.go, pkg/epp/flowcontrol/controller/internal/processor.go, pkg/epp/flowcontrol/controller/internal/processor_test.go, pkg/epp/scheduling/framework/plugins/scorer/lora_affinity_test.go, pkg/epp/scheduling/scheduler.go
Ran `make fmt-imports` as part of #1237.
Changed files were unrelated and therefore outside the scope of that PR, hence committing separately across all packages.
Q: do/should we fail PRs by integrating `make fmt-imports` as a mandatory check (similar to `go mod tidy`)?
=> Fixes for `make fmt-imports`

Makefile
The #1010 skip the EPP image build see the following command.
```
❯ make image-push
make: Nothing to be done for 'image-push'.
```
Tried #1286 to enable multi-platform, unfortunately it does not work. So I think we should revert the original one first to unblock.
=> revert #1010 to resume new main EPP image build

pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go
In high concurrency tests, EPP would hard crash with a stack trace:
```
panic: runtime error: index out of range [-1]
goroutine 8462092 [running]:
math/rand.(*rngSource).Uint64(...)
/usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000000000?)
/usr/local/go/src/math/rand/rng.go:234 +0x85
math/rand.(*Rand).Int63(...)
/usr/local/go/src/math/rand/rand.go:96
math/rand.(*Rand).Uint32(...)
/usr/local/go/src/math/rand/rand.go:99
math/rand.(*Rand).int31n(0xc0008eff50, 0x3)
/usr/local/go/src/math/rand/rand.go:162 +0x31
math/rand.(*Rand).Shuffle(0xc0008eff50, 0xc001be6c60?, 0xc0020ef030)
/usr/local/go/src/math/rand/rand.go:264 +0x79
sigs.k8s.io/gateway-api-inference-extension/pkg/epp/scheduling/framework/plugins/picker.(*RandomPicker).Pick(0xc000b0c6c0, {0x2636070?, …
```
=> Removing concurrency issues from Random Picker

site-src/guides/index.md
Bumps the kgateway version in the quickstart guide.
=> Docs: Bumps kgateway Version in Quickstart

conformance/reports/v0.5.1/gateway/kgateway/README.md, conformance/reports/v0.5.1/gateway/kgateway/inference-v2.0.4-report.yaml
Adds a conformance report for kgateway and reproducer steps.
=> Conformance: Adds Report for kgateway

site-src/guides/index.md
fix: #1344
When installing the control plane using `./istioctl` in the current guide, the GIE feature is not enabled. This issue can be resolved by setting an environment variable during installation.
=> docs: Enable GIE in Istio installation command

apix/v1alpha2/inferenceobjective_types.go, config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml, test/testdata/inferencepool-with-model-hermetic.yaml
This PR sets the default `poolRef` group of InferenceObjective from `inference.networking.x-k8s.io` to `inference.networking.x-k8s.io`. This aligns with the default InferencePool group used by the EPP binary.
=> InferenceObjective: Updates `PoolRef` Group Version

apix/v1alpha2/inferenceobjective_types.go, apix/v1alpha2/zz_generated.deepcopy.go, client-go/applyconfiguration/apix/v1alpha2/inferenceobjectivespec.go, config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml, config/manifests/inferenceobjective.yaml, config/manifests/regression-testing/inferenceobjective.yaml, conformance/tests/epp_unavailable_fail_open.yaml, conformance/tests/gateway_following_epp_routing.yaml, pkg/epp/controller/inferenceobjective_reconciler_test.go, pkg/epp/datastore/datastore_test.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/util/testing/wrappers.go, site-src/guides/adapter-rollout.md, site-src/guides/inferencepool-rollout.md, site-src/guides/serve-multiple-lora-adapters.md, test/e2e/epp/e2e_test.go, test/testdata/inferencepool-with-model-hermetic.yaml, test/utils/wrappers.go
Fixes: #1243
This PR changes Criticality to an optional int field; setting & documenting behavior handling the optional state. This is the final PR for the code-related API changes. Documentation still needs to be updated, and a small configuration issue was created (documented in comments). 
FYI CC: @ahg-g @nirrozenbaum @danehans
=> Modifying Criticality; from string, to int

cmd/epp/runner/runner.go, pkg/epp/backend/metrics/logger.go, pkg/epp/backend/metrics/pod_metrics_test.go, pkg/epp/backend/metrics/types.go, pkg/epp/controller/inferenceobjective_reconciler_test.go, pkg/epp/controller/inferencepool_reconciler_test.go, pkg/epp/controller/pod_reconciler_test.go, pkg/epp/datastore/datastore_test.go, pkg/epp/metrics/collectors/inference_pool.go, pkg/epp/metrics/collectors/inference_pool_test.go, pkg/epp/requestcontrol/director.go, pkg/epp/requestcontrol/director_test.go, pkg/epp/saturationdetector/saturationdetector.go, test/integration/epp/hermetic_test.go, test/utils/server.go
There are three changes in this PR:
- delete `metricsStalenessThreshold` field in `PodMetricsFactory` struct and  also delete this in `NewPodMetricsFactory` func
- rename `AllPodPredicate` to `AllPodsPredicate` to fix typo
- add `PodsWithFreshMetrics` func to initialize a predicate function for `PodList`
/cc @liu-cong @nirrozenbaum
=> cleanup: fix typo and delete useless parameter

pkg/epp/flowcontrol/contracts/mocks/mocks.go, pkg/epp/flowcontrol/contracts/registry.go, pkg/epp/flowcontrol/controller/internal/filter.go, pkg/epp/flowcontrol/controller/internal/filter_test.go, pkg/epp/flowcontrol/controller/internal/item_test.go, pkg/epp/flowcontrol/controller/internal/processor.go, pkg/epp/flowcontrol/controller/internal/processor_test.go, pkg/epp/flowcontrol/framework/mocks/mocks.go, pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/besthead/besthead_test.go, pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/functional_test.go, pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/roundrobin/roundrobin.go, pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/roundrobin/roundrobin_test.go, pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/fcfs/fcfs_test.go, pkg/epp/flowcontrol/framework/plugins/queue/benchmark_test.go, pkg/epp/flowcontrol/framework/plugins/queue/functional_test.go, pkg/epp/flowcontrol/framework/plugins/queue/maxminheap/maxminheap_test.go, pkg/epp/flowcontrol/framework/policies.go, pkg/epp/flowcontrol/registry/doc.go, pkg/epp/flowcontrol/registry/managedqueue.go, pkg/epp/flowcontrol/registry/managedqueue_test.go, pkg/epp/flowcontrol/registry/shard.go, pkg/epp/flowcontrol/registry/shard_test.go, pkg/epp/flowcontrol/types/flow.go, pkg/epp/flowcontrol/types/mocks/mocks.go, pkg/epp/flowcontrol/types/request.go
This PR refactors the flow control system to establish the composite `types.FlowKey` (ID + Priority) as the canonical, immutable identifier for a flow instance. This is a direct result of critical feedback and discussions on the open registry PR #1319 , which revealed a fundamental misalignment between the implementation's data model and the API's intended contract.
The previous model treated a flow's priority as a mutable attribute, which required a complex state machine for handling "graceful updates" (managing `active` vs. `draining` states, generation counters, etc.). This PR replaces that model with a simpler, more robust architecture where a flow instance is uniquely and immutably defined by its `FlowKey`.
This tracks #674 
---
-   **Introduces `types.FlowKey`:** A new struct …
=> refactor(flowcontrol): Adopt Composite FlowKey as Primary Identifier

conformance/tests/epp_unavailable_fail_open.go, conformance/tests/gateway_following_epp_routing.go
Adds the "x-gateway-inference-objective" metadata header to conformance tests that specify an InferenceObjective.
Fixes #1352
=> Conformance: Adds InferenceObjective Request Header

conformance/resources/resourcename.go, conformance/tests/epp_unavailable_fail_open.go, conformance/tests/gateway_following_epp_routing.go, pkg/epp/scheduling/framework/plugins/test/consts.go, pkg/epp/scheduling/framework/plugins/test/filter/filter_test.go, pkg/epp/scheduling/framework/plugins/test/filter/request_header_based_filter.go
The main purpose is just to move `HeaderTestEppEndPointSelectionKey`. I also move `InferenceObjName` to central place together in this PR since it's simple.
A new file, `consts.go`, has been created within the test plugins package (pkg/epp/scheduling/framework/plugins/test) to centralize constants used by the EPP scheduling framework's test plugins for conformance tests.
These changes help to make the conformance testing suite more modular and less dependent on implementation-specific packages. Otherwise, if we want to introduce the conformance test to internal CI/CD pipeline we have to copy a lot of not needed EPP packages.
=> refactor(conformance): Relocate constants to minimize package dependencies

pkg/epp/backend/metrics/fake.go, pkg/epp/backend/metrics/logger.go, pkg/epp/backend/metrics/metrics_state.go, pkg/epp/backend/metrics/pod_metrics.go, pkg/epp/backend/metrics/pod_metrics_test.go, pkg/epp/backend/metrics/types.go, pkg/epp/backend/pod.go, pkg/epp/datalayer/endpoint.go, pkg/epp/datalayer/factory.go, pkg/epp/datastore/datastore.go
This PR introduces several interfaces and wrappers to allow users of `backend/metrics` code to work with `datalayer` as an implementation. 
- Redefined structures in `backend` and `metrics` (e.g., `MetricsState`, `PodMetrics`, `Pod`) as aliases to corresponding types in `datalayer`
- Introduced interfaces to decouple rest of system (e.g., `datastore`) from the concrete implementations of `backend/metrics`.
For example, `EndpointFactory` interface variable in datastore instead of a concrete `PodMetricsFactory` struct.
- Added no-op methods to `podMetrics` so it implements the expected extended attribute interface (another option is to define Endpoint without it and type assert from `Endpoint` to (e.g.,) `EndpointWithExtendedAttributes` inside the datalayer).
- `RefreshLoop` handling is now …
=> Pluggable data layer: transition `backend/metrics` to use type aliases from `datalayer` package

site-src/guides/index.md
fix #1249
The CRD on the current `dev` branch is mismatched with the EPP in the implementation. Using the latest release, **`tag:0.5.1`**, will avoid this issue.
=> docs: match Inference Extension CRDs

.github/PULL_REQUEST_TEMPLATE.md
Adds a PR template to provide uniformity to pull requests.
=> Tooling: Adds PR Template

hack/release-quickstart.sh
Updated `hack/release-quickstart.sh`:
- Updates default values of vLLM images.
- Updates path to conformance base manifest.
/kind bug
N/A
```release-note
NONE
```
=> Fixes Quickstart Script

cmd/epp/runner/health.go
/kind bug
/kind failing-test
**What this PR does / why we need it:**
When High Availability (HA) is enabled on GKE, the GCP backend service health check uses an empty string service name, which incorrectly causes all pods to be reported as healthy, regardless of their actual readiness state.
This PR fixes this behavior by mapping the empty string health check to use the pod's readiness probe status. This ensures that the GCP backend service only considers ready pods as healthy and prevents traffic from being routed to pods that are not yet able to serve requests. This change does not affect the standard Kubernetes liveness and readiness probes.
**Which issue(s) this PR fixes:**
Fixes failing-test on GKE for #1337 
**Does this PR introduce a user-facing …
=> Fix: Handle empty string healthcheck as readiness healthcheck

pkg/epp/config/loader/configloader_test.go, pkg/epp/config/loader/defaults.go, pkg/epp/plugins/plugin_state_test.go, pkg/epp/scheduling/framework/plugins.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, pkg/epp/scheduling/framework/scheduler_profile.go, pkg/epp/scheduling/framework/scheduler_profile_test.go, pkg/epp/scheduling/scheduler_test.go, test/integration/epp/hermetic_test.go
This PR deprecates PostCycle extension point from scheduling framework.
instead of calling PostCycle in prefix plugin, this was changed to PreRequest.
Additionally, the use of CycleState was replaced with PluginState, since PreRequest is not part of the scheduling cycle and therefore the state cannot be shared between the extension point with that mechanism.
tests were updated accordingly.
please pay attention that I do plan on having all the extension points defined in the same plugins package, which is currently not the case (I don't like the fact that prefix plugin imports requestcontrol). 
due to the fact that a release is close, this change will be pushed at the beginning of the next release cycle (after first RC of current release) to avoid big changes in plugins before the release.
=> depreacte post cycle from scheduling framework

conformance/resources/base.yaml
/kind bug
Optionally add one or more of the following kinds if applicable:
/kind failing-test
/area conformance-test
Fixes the seconday InferencePool's selector to select secondary backend echo servers instead of primary backends.
Fixes #1418
```release-note
NONE
```
=> Conformance: Fixes Secondary InferencePool Selector

Makefile, bbr.Dockerfile
/kind bug
This PR fixes several minor issues in the Makefile and Dockerfile:
* Fix missing . prefix for .PHONY declarations in Helm targets
* Use `YQ_VERSION` variable instead of hardcoded version in yq target
* Update `bbr.Dockerfile` to use `golang:1.24` (consistent with main Dockerfile)
These changes improve consistency and follow proper Makefile syntax conventions.
Fixes #
```release-note
NONE
```
=> Fix Makefile syntax and version consistency

pkg/epp/scheduling/framework/scheduler_profile.go
I've been asked several times about the ability to debug specific scorers when running EPP.
to help debug, this PR adds logging (in trace level) of a score per pod of a scorer.
=> trace logging for scores per pod

cmd/epp/runner/runner.go
Fix #1367
env vars are not needed for cmd-line args. this PR removes this duplication. 
another minor change is defining cmd-arg in single line instead of 3 lines, which makes it hard for a reader to find the cmd-line args. no change in cmd-line args except for removing "new lines".
=> remove env vars for cmd-lind args

config/charts/inferencepool/README.md, config/charts/inferencepool/values.yaml
Follow-up of 
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1302
Couple of review comments were unaddressed.
=> Cleanup helm flags which have default values from values yaml

config/charts/inferencepool/templates/epp-deployment.yaml
The `config-file` default is empty, we need to specify it in the charts, otherwise we get error:
```
{"level":"error","ts":"2025-08-22T22:38:56Z","logger":"setup","caller":"runner/runner.go:242","msg":"failed to create scheduler","error":"scheduler config must be set either by config api or through code","stacktrace":"sigs.k8s.io/gateway-api-inference-extension/cmd/epp/runner.(*Runner).Run\n\t/src/cmd/epp/runner/runner.go:242\nmain.main\n\t/src/cmd/epp/main.go:31\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283"}
```
=> Fix epp startup error due to missing plugin config file flag

site-src/guides/index.md
This PR addresses issue #1208 to ensure getting started guide uses helm charts
=> Update inference gateway public docs to use helm charts

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
=> fix: first hash of prefix cache with same model name

cmd/epp/runner/runner.go
/kind cleanup
Enables Mutex and Block profiles by default when pprof is enabled
=> adding mutex and contention profile gathering

apix/v1alpha2/inferencepool_conversion.go, apix/v1alpha2/inferencepool_conversion_test.go
/kind bug
While doing v1alpha2 and v1 infPool conversion, if the condition slice is empty we are always adding an empty placeholder slice. However, this is not consistent with the "omitempty"
```
// +optional
// +listType=map
// +listMapKey=type
// +kubebuilder:validation:MaxItems=8
Conditions []metav1.Condition `json:"conditions,omitempty"`
```
NONE
NONE
```release-note
```
=> remove empty condition list when doing v1 and v1alpha2 conversion.

apix/v1alpha2/inferencepool_conversion.go, apix/v1alpha2/inferencepool_conversion_test.go
/kind cleanup
- Drop the v1alpha2 synthetic parent `{Kind: "Status", Name: "default"}` when converting to v1; do not synthesize it when converting from v1.
- Filter the v1alpha2 default condition `Accepted{Status: Unknown, Reason: Pending}` when converting to v1.
- Map Accepted reasons both ways: `NotSupportedByGateway` <-> `NotSupportedByParent` (preserve other reasons like `HTTPRouteNotAccepted`).
- Normalize empty condition sets to `nil` in v1 to avoid emitting empty condition arrays.
- Minor polish: typo fix in `isV1Alpha2DefaultCondition`, small helper funcs for parent/condition detection and reason mapping.
N/A
```release-note
NONE …
```
=> Updates InferencePool API Conversion Code

docs/proposals/002-api-proposal/README.md, docs/proposals/003-model-server-protocol/README.md, docs/proposals/004-endpoint-picker-protocol/README.md, docs/proposals/006-scheduler/README.md, docs/proposals/0602-prefix-cache-aware-routing-proposal/README.md, docs/proposals/0683-epp-architecture-proposal/README.md, docs/proposals/0845-scheduler-architecture-proposal/README.md, docs/proposals/1023-data-layer-architecture/README.md, docs/proposals/1199-inferencemodel-api-evolution/README.md
A quick update to all the proposal's statuses
=> Updating proposal statuses

conformance/resources/resourcename.go, conformance/tests/epp_unavailable_fail_open.go, conformance/tests/epp_unavailable_fail_open.yaml, conformance/tests/gateway_following_epp_routing.go, conformance/tests/gateway_following_epp_routing.yaml
/kind bug
/area conformance-test
1. Now the main inferenceObjective is using `priority` instead of `criticality` so currently the inferenceObjective is never applied successfully.
2. the inferenceObjective and the header is not needed since this change(https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/38462653aa0531e287f0ba79b863603c950b9155/pkg/epp/requestcontrol/director.go#L219-L222) is introduced in EPP. The default priority will be 0 which will bypass the saturation check natively.
Fixes #1002
NONE
=> fix(conformance): remove the inferenceObjective dependency compeletely.

pkg/epp/scheduling/framework/plugins/multi/prefix/indexer.go, pkg/epp/scheduling/framework/plugins/multi/prefix/indexer_test.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
/kind cleanup
context.TODO was used in a periodic go routine of the indexer, updated it to use a context.
related to #
```release-note
NONE
```
=> use context in indexer go routine instead of context.TODO

conformance/conformance.go
Currently, the conformance report is using hard-coded variable `BundleVersion` in `version.go`. This PR get the version from annotation `BundleVersionAnnotation` of installed CRDs.
Tested locally, the following is an example generated report, I installed v0.5.0 CRDs.
```
GatewayAPIInferenceExtensionVersion: v0.5.0
apiVersion: gateway.networking.k8s.io/v1
date: "2025-07-22T05:30:18Z"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.2.1
implementation:
contact:
- gke-gateway-dev@google.com
organization: GKE
project: gke-gateway
url: https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api
version: TBD
kind: ConformanceReport
mode: default
profiles:
- core:
result: success
statistics:
Failed: 0
Passed: 9
Skipped: 0
name: Gateway
summary: Core tests succeeded.
```
A follow up PR …
=> feat(conformance): Use CRD annotation to populate the ConformanceReport GatewayAPIInferenceExtensionVersion

pkg/epp/handlers/server.go, pkg/epp/plugins/plugin_state.go, pkg/epp/server/server_test.go, test/integration/epp/hermetic_test.go, test/integration/util.go
/kind bug
This PR fixes a bug of EPP crashing in high scale. the bug happens due to requestID being empty and then prefix plugin maps different requests to the same PluginState entry, which results in different go routines trying to write to the same map concurrently. more details in issue #1489.
This PR guarantees requestID is always set. if it's not supplied as a header, we generate it while handling the request headers, before starting to handle the request body.
Fixes #1489
```release-note
NONE
```
=> if request id was not supplied in header, generate uuid

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
/kind bug
This PR adds back the writing of Prefix State to CycleState. 
When switching to use `PluginState` instead of `CycleState` in Prefix plugin, I forgot that PD profile handler in llm-d consumes the prefix state through `CycleState` variable. 
This PR does a temporary fix to write the state to both `PluginState` and `CycleState` and is only meant to solve the issue for llm-d release.
once we release, I will work on a long term fix - exposing in `PluginState` the fields that are needed by the plugin extension points, and exposing in `CycleState` a different struct, that may be beneficial for other plugins, like sharing the hit percentage per endpoint (which is used by llm-d). This fix will also solve a different …
=> prefix state temp fix - write state to both plugin state and cycle state

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/epp-deployment.yaml, config/charts/inferencepool/values.yaml
/kind feature
This PR adds support for configuring `affinity` and `tolerations` in the epp-deployment chart template.
Fixes #
```release-note
NONE
```
=> feat(helm): add affinity and tolerations to epp-deployment

site-src/index.md
In https://gateway-api-inference-extension.sigs.k8s.io/#concepts-and-definitions, the `Prefix Cache` and `LoRA Adapters` missed web links.
=> typo: add vLLM Prefix Cache & LoRA Adapters links

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/scheduler_profile.go
Small updates to logging and adding goroutine for function call that has high lock contention, but doesnt impact the request routine, so spinning up into another thread. 
These were found during scale testing, can include an extensive write-up if needed, but the tl;dr is: 
- the logging issues were because golang still calls sprintf even if the log level isnt enabled, which was creating CPU hotspots, we are now letting the logging library handle all that under the hood.
- The indexer.Add func can have a high level of lock contention if all the prefixes are different, so moving the call to its own routine allows requests to continue without being blocked by indexing.
=> Perf updates

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go
/kind cleanup
follow up to #1523 for updating the logging perf issue in few more places
Fixes #
```release-note
NONE
```
cc: @kfswain @liu-cong
=> follow up - improving logging perf issues in few more places

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
Fixes: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1529
Adding a waitGroup should not impact prod code as we do not wait on this WG anywhere in the system, just allows unit tests to be synchronous
=> Fixing test flake

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/epp-deployment.yaml, config/charts/inferencepool/templates/gke.yaml, config/charts/inferencepool/templates/rbac.yaml
/kind bug
/kind helm
The current GKE helm chart is not working well with v1alpha2 version.
Verified the current fix working by the following step
1. create model server, use model sim for easy deploy
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: vllmsim
spec:
replicas: 1
selector:
matchLabels:
app: vllmsim
template:
metadata:
labels:
app: vllmsim
spec:
containers:
- name: vllm-sim
image: ghcr.io/llm-d/llm-d-inference-sim:v0.3.0
imagePullPolicy: Always
args:
- --model
- meta-llama/Llama-3.1-8B-Instruct
- --port
- "8000"
- --max-loras
- "2"
- --lora-modules
- '{"name": "food-review-1"}'
env:
- name: POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: NAMESPACE
valueFrom:
fieldRef:
fieldPath: …
```
=> fix helm chart support for gke v1alpha2.

pkg/epp/scheduling/framework/plugins/picker/common.go, pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go, pkg/epp/scheduling/framework/plugins/picker/random_picker.go
/kind cleanup
Merge shuffle score pods logic
Fixes #
```release-note
```
=> Merge shuffle score pods logic

pkg/epp/scheduling/framework/plugins/picker/picker_test.go
/kind flake
Fix a test flake of random weighted picker.
This fix is based on expected probabilities with some tolerance to make sure the actual random sampling is close enough to the expected results. more on the numbers:
🔹 Setup
- Suppose expected probability = 𝑝.
- Number of trials = 𝑛 = 10000
- The observed count follows a binomial distribution:
𝑋∼Binomial(𝑛,𝑝)
- Observed frequency = 𝑋/𝑛
- Standard deviation (σ) of observed frequency is:
𝜎=_sqrt_(𝑝(1−𝑝)/𝑛)
🔹 Example: worst-case variance
The variance is largest at 𝑝=0.5
𝜎=_sqrt_(0.5⋅0.5/10000)≈0.005
So the natural “jitter” is about ±0.5 percentage points.
🔹 With tolerance = ±5% (0.05)
- Allowed range = expected ±0.05.
- That is 10× wider than σ.
In normal distribution …
=> fix flake in weighted random picker

config/charts/inferencepool/templates/_helpers.tpl, config/charts/inferencepool/templates/rbac.yaml
What type of PR is this?
/kind bug
What this PR does / why we need it:
Which issue(s) this PR fixes:
The root cause of https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1393 as an alternative solution. The issue behind this is that you cannot install 2 releases of the GIE inferencepool chart with the same release name but in different namespaces because helm fights over the ownership of the cluster RBAC. This is a key issue we have in llm-d where people try to deploy similar examples in parallel but cannot.
Does this PR introduce a user-facing change?:
There are no API changes here, it simply creates a separate naming convention for cluster scoped RBAC so that multiple releases with the same name but different namespaces can co-exist.
We will revert #1545 and close …
=> Main uniquely name crbac

pkg/epp/flowcontrol/contracts/mocks/mocks.go, pkg/epp/flowcontrol/contracts/registry.go, pkg/epp/flowcontrol/controller/internal/filter.go, pkg/epp/flowcontrol/controller/internal/filter_test.go, pkg/epp/flowcontrol/controller/internal/processor.go, pkg/epp/flowcontrol/controller/internal/processor_test.go, pkg/epp/flowcontrol/framework/mocks/mocks.go, pkg/epp/flowcontrol/framework/policies.go, pkg/epp/flowcontrol/registry/config.go, pkg/epp/flowcontrol/registry/managedqueue_test.go, pkg/epp/flowcontrol/registry/registry.go, pkg/epp/flowcontrol/registry/registry_test.go, pkg/epp/flowcontrol/registry/shard.go, pkg/epp/flowcontrol/registry/shard_test.go, pkg/epp/flowcontrol/types/flow.go
/kind bug or refactor
This PR updates the type of priority from uint to int in flow control to ensure its in sync with what we have in API spec. 
Presently, the priority in API spec is an [int](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/fb77ef28d7d66ecaedfac033c0dcc746fe62b6d7/apix/v1alpha2/inferenceobjective_types.go#L80) whereas in the EPP flow control is an [unsigned int](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/8446c07bf2515206f61da2b467e2e3e652dcf876/pkg/epp/flowcontrol/types/flow.go#L44)
Fixes #1473
```release-note
```
cc @LukeAVanDrie
=> Update priority in EPP flow control from uint to int

config/charts/inferencepool/templates/_helpers.tpl, config/charts/inferencepool/templates/rbac.yaml
Reversion PR, allowing merging to main instead in #1564 
Relates to:
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1545#issuecomment-3275563940
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1563#issuecomment-3275577370
- https://llm-d.slack.com/archives/C08SBNRRSBD/p1757519952731199
cc @kfswain @ahg-g @liu-cong
=> Revert "uniquely name CRBAC (#1545)"

internal/runnable/grpc.go, pkg/bbr/handlers/server.go, pkg/bbr/server/runserver.go, pkg/epp/controller/inferenceobjective_reconciler.go, pkg/epp/controller/inferencepool_reconciler.go, pkg/epp/controller/pod_reconciler.go, pkg/epp/handlers/response.go, pkg/epp/handlers/server.go, pkg/epp/server/runserver.go
/kind cleanup
Remove unneeded logging right before returning error.
How I decide which logging is useful:
- Useful: logging with extra info
https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/8b154baffd35e1c4ad1dcd131f1cbcac04ddc304/cmd/bbr/main.go#L98-L99
- Not useful: logging which say "something failed"
Would be great if you can feedback if my decision is reasonable. Thanks team.
Fixes #334
```release-note
NONE
```
=> chore: remove unneeded logging before returning error

pkg/epp/flowcontrol/config.go, pkg/epp/flowcontrol/config_test.go, pkg/epp/flowcontrol/controller/config.go, pkg/epp/flowcontrol/controller/config_test.go, pkg/epp/flowcontrol/controller/controller.go, pkg/epp/flowcontrol/controller/controller_test.go, pkg/epp/flowcontrol/registry/config.go, pkg/epp/flowcontrol/registry/config_test.go, pkg/epp/flowcontrol/registry/registry.go, pkg/epp/flowcontrol/registry/registry_test.go, pkg/epp/flowcontrol/registry/shard_test.go
/kind cleanup
This PR refactors the configuration handling within the `pkg/epp/flowcontrol` package and its sub-packages (`controller`, `registry`) to improve robustness, consistency, and clarity.
The core of the refactoring replaces the `newConfig` factory function pattern with a public `ValidateAndApplyDefaults` method on the configuration structs. This change:
- Makes the validation and defaulting logic more explicit and discoverable.
- Promotes immutability by returning a new, validated configuration object instead of mutating the receiver.
- Simplifies the constructors for `FlowController` and `FlowRegistry`, as they now expect a pre-validated configuration.
- Introduces a new top-level `flowcontrol.Config` to …
=> refactor: flow control config

config/manifests/gateway/agentgateway/httproute.yaml, config/manifests/gateway/envoyaigateway/httproute.yaml, config/manifests/gateway/istio/httproute.yaml, config/manifests/gateway/kgateway/httproute.yaml
Updates HTTPRoute manifests for all gateways other than GKE to use v1 InferencePool as a backendRef.
/kind bug
/kind documentation
This PR is needed because a user cannot complete the quickstart guide for all gateways other than GKE. Additionally, we do not want to promote the alpha InferencePool API.
Fixes #1602
```release-note
NONE
```
=> Updates gateway manifests for v1 InferencePool

pkg/epp/config/loader/configloader_test.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go, site-src/guides/epp-configuration/config-text.md, site-src/guides/epp-configuration/prefix-aware.md, test/testdata/configloader_1_test.yaml
This is a breaking change.
Fixes #1559
```release-note
Rename prefix scorer HashBlockSize to BlockSize
```
=> Rename prefix scorer HashBlockSize to BlockSize

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/epp-deployment.yaml, config/charts/inferencepool/templates/gke.yaml
/kind bug
In addition to fix the bug, I did the following improvements:
1. Adjusted the gke health check and EPP readiness check to every 2s instead of 5s, this allows faster switch over to the new EPP leader (in my tests this goes from 10-15s to less than 5s).
2. Consolidated all HA related config to a single `enableLeaderElection` flag. Previous to enable HA you need to do 3 things:  1. set `enableLeaderElection=true` 2. set `replicas=3` 3. set `flags.ha-enable-leader-election=true`. This is hard to get right.
Fixes #1619 
```release-note
```
=> Consolidate ha config into a single enableLeaderElection, also fix rolling update stuck bug

config/charts/inferencepool/templates/gke.yaml
/kind bug
This is discovered by the Lohi Pipline, where we always use the main helm to install inferencePool and it failed at finding GCPBackendPolicy:  
Current inferecePool Helm install will return warning and missing the GCPBackendPolicy for logging. The following as an exmple.
```
❯ export NAMESPACE=inference-demo
export HELM_RELEASE_NAME=infpool-gemma-2b
❯ helm upgrade -i $HELM_RELEASE_NAME \
config/charts/inferencepool \
-n $NAMESPACE \
--create-namespace \
--set inferencePool.modelServers.matchLabels.app=vllm-gemma2b \
--set provider.name=gke \
--set inferenceExtension.monitoring.gke.enabled=true
Release "infpool-gemma-2b" does not exist. Installing it now.
**I0920 00:19:58.644743 1622628 warnings.go:110] …
```
=> fix missing GCPBakendPolicy.

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/epp-deployment.yaml, config/charts/inferencepool/templates/leader-election-rbac.yaml
/kind cleanup
use a single field (replicas) in the helm chart to decide whether EPP should run in HA mode or not.
this change verifies replicas is still overridable, and also verifies helm cannot be used to set active active mode. 
if one uses replicas with a value greater than 1, helm will set HA in active passive mode.
Fixes #
```release-note
None
```
=> use replicas field in helm to decide if EPP should run in HA mode

config/charts/inferencepool/README.md, config/charts/inferencepool/templates/istio.yaml, config/charts/inferencepool/values.yaml
=> enable istio as a provider + configuring destinationRule

pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go, pkg/epp/scheduling/types/types.go, pkg/epp/util/request/body_test.go
/kind feature
support vLLM cache salting in prefix aware scorer
Fixes #1631
```release-note
support vLLM cache salting in prefix aware scorer
```
=> support vLLM cache salting in prefix aware scorer
